# Generated by Django 6.0.1 on 2026-01-28 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0005_anexodemanda_comentariodemanda_demanda_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('cor', models.CharField(default='#6366f1', help_text='Cor em hex para identificação visual', max_length=7)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nome'],
            },
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='workspaces',
        ),
        migrations.AlterModelOptions(
            name='cargo',
            options={'ordering': ['empresa', 'nome'], 'verbose_name': 'Cargo', 'verbose_name_plural': 'Cargos'},
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='is_gestor',
            field=models.BooleanField(default=False, help_text='Gestor pode ver tarefas de todos e criar demandas'),
        ),
        migrations.AlterUniqueTogether(
            name='cargo',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cargo',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='empresas',
            field=models.ManyToManyField(blank=True, related_name='pessoas', to='core.empresa'),
        ),
        migrations.AlterUniqueTogether(
            name='cargo',
            unique_together={('empresa', 'nome')},
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='workspace',
        ),
        migrations.DeleteModel(
            name='Workspace',
        ),
    ]
