# Generated by Django 6.0.1 on 2026-01-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_empresa_remove_pessoa_workspaces_alter_cargo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PessoaExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('telefone', models.CharField(blank=True, help_text='WhatsApp com DDD', max_length=20)),
                ('empresa_nome', models.CharField(blank=True, help_text='Empresa do contato', max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pessoa Externa',
                'verbose_name_plural': 'Pessoas Externas',
                'ordering': ['nome'],
            },
        ),
    ]
