# Generated by Django 5.2.10 on 2026-02-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pessoaexterna'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='receber_lembrete_financeiro',
            field=models.BooleanField(default=False, help_text='Receber lembrete de contas a pagar via WhatsApp'),
        ),
    ]
