# Generated by Django 5.2.10 on 2026-02-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_receber_lembrete_financeiro'),
    ]

    operations = [
        # Remove o campo boolean antigo
        migrations.RemoveField(
            model_name='pessoa',
            name='receber_lembrete_financeiro',
        ),
        # Adiciona o novo campo ManyToMany
        migrations.AddField(
            model_name='pessoa',
            name='empresas_lembrete_financeiro',
            field=models.ManyToManyField(blank=True, help_text='Empresas das quais recebe lembrete de contas a pagar via WhatsApp', related_name='pessoas_lembrete_financeiro', to='core.empresa'),
        ),
    ]
