# Generated by Django 5.2.10 on 2026-04-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_itemcofre'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='empresas_gestor',
            field=models.ManyToManyField(blank=True, help_text='Empresas onde esta pessoa é gestora (nas demais é funcionário)', related_name='gestores', to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='is_gestor',
            field=models.BooleanField(default=False, help_text='Legado - usar empresas_gestor'),
        ),
    ]
