# Generated by Django 5.2.10 on 2026-04-04 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_empresas_gestor'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacaoInApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('demanda', 'Nova Demanda'), ('tarefa', 'Nova Tarefa'), ('comentario', 'Comentário'), ('prazo', 'Prazo Vencendo'), ('convite', 'Convite'), ('geral', 'Geral')], default='geral', max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.CharField(blank=True, max_length=500)),
                ('url', models.CharField(blank=True, help_text='URL para redirecionar ao clicar', max_length=500)),
                ('lida', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_inapp', to='core.pessoa')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-criado_em'],
            },
        ),
    ]
