# Generated by Django 5.2.10 on 2026-04-04 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_notificacao_inapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='PapelEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('gestor', 'Gestor'), ('colaborador', 'Colaborador'), ('executante', 'Executante')], default='executante', max_length=15)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papeis_pessoas', to='core.empresa')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papeis_empresa', to='core.pessoa')),
            ],
            options={
                'verbose_name': 'Papel na Empresa',
                'verbose_name_plural': 'Papéis nas Empresas',
                'unique_together': {('pessoa', 'empresa')},
            },
        ),
    ]
