# Generated by Django 5.2.10 on 2026-04-04 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_solicitacoes_cliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='user',
        ),
        migrations.CreateModel(
            name='ContatoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('papel', models.CharField(choices=[('dono', 'Dono / Responsável'), ('funcionario', 'Funcionário')], default='funcionario', max_length=15)),
                ('funcao', models.CharField(blank=True, help_text='Ex: Criativo, Financeiro, TI', max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='core.cliente')),
                ('user', models.OneToOneField(blank=True, help_text='User para login no portal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contato_cliente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contato do Cliente',
                'verbose_name_plural': 'Contatos dos Clientes',
                'ordering': ['-papel', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='contato',
            field=models.ForeignKey(blank=True, help_text='Pessoa específica que deve executar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes', to='core.contatocliente'),
        ),
    ]
