# Generated by Django 5.2.10 on 2026-04-04 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_contato_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivosolicitacao',
            name='enviado_por_nome',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='arquivosolicitacao',
            name='tamanho',
            field=models.IntegerField(default=0, help_text='Tamanho em bytes'),
        ),
        migrations.CreateModel(
            name='ComentarioSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor_nome', models.CharField(max_length=200)),
                ('autor_is_cliente', models.BooleanField(default=False)),
                ('texto', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='core.solicitacao')),
            ],
            options={
                'ordering': ['criado_em'],
            },
        ),
    ]
