# Generated by Django 5.2.10 on 2026-04-04 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_comentario_solicitacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('criada_por_cliente', models.BooleanField(default=False)),
                ('ordem', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastas', to='core.cliente')),
                ('pasta_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subpastas', to='core.pastacliente')),
            ],
            options={
                'verbose_name': 'Pasta do Cliente',
                'verbose_name_plural': 'Pastas dos Clientes',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ArquivoPasta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='clientes/%Y/%m/')),
                ('nome_original', models.CharField(max_length=255)),
                ('tamanho', models.IntegerField(default=0)),
                ('enviado_por', models.CharField(blank=True, max_length=200)),
                ('enviado_por_cliente', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos_pasta', to='core.pastacliente')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PastaTemplateEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ordem', models.IntegerField(default=0)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastas_template', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Template de Pasta',
                'verbose_name_plural': 'Templates de Pastas',
                'ordering': ['ordem', 'nome'],
                'unique_together': {('empresa', 'nome')},
            },
        ),
    ]
