# Generated by Django 5.2.10 on 2026-04-04 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_pastas_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivosolicitacao',
            name='pasta',
            field=models.ForeignKey(blank=True, help_text='Pasta onde o arquivo foi organizado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arquivos_solicitacao', to='core.pastacliente'),
        ),
    ]
