# Generated by Django 5.2.10 on 2026-04-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_pasta_to_arquivo_solicitacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='data_inicio_contrato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_renovacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='dia_vencimento',
            field=models.IntegerField(blank=True, help_text='Dia do mês que vence (1-31)', null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('boleto', 'Boleto'), ('pix', 'Pix'), ('cartao', 'Cartão'), ('transferencia', 'Transferência'), ('outro', 'Outro')], default='boleto', max_length=15),
        ),
        migrations.AddField(
            model_name='cliente',
            name='gateway_id',
            field=models.CharField(blank=True, help_text='ID no gateway de pagamento (Asaas, etc)', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='segmento',
            field=models.CharField(blank=True, choices=[('ecommerce', 'E-commerce'), ('clinica', 'Clínica / Saúde'), ('restaurante', 'Restaurante / Alimentação'), ('industria', 'Indústria'), ('servicos', 'Serviços'), ('varejo', 'Varejo / Loja Física'), ('educacao', 'Educação'), ('imobiliaria', 'Imobiliária'), ('outro', 'Outro')], default='outro', max_length=15),
        ),
        migrations.AddField(
            model_name='cliente',
            name='servicos',
            field=models.TextField(blank=True, help_text='Serviços contratados (ex: Tráfego Pago, Social Media, Criativos)'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='status_contrato',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('pausado', 'Pausado'), ('inadimplente', 'Inadimplente'), ('cancelado', 'Cancelado')], default='ativo', max_length=15),
        ),
        migrations.AddField(
            model_name='cliente',
            name='valor_mensal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fee mensal', max_digits=10, null=True),
        ),
    ]
