# Generated by Django 5.2.10 on 2026-04-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_contrato_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='contatocliente',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='contatocliente',
            name='telefone',
            field=models.CharField(blank=True, help_text='WhatsApp / Celular', max_length=20),
        ),
    ]
