# Generated by Django 5.2.10 on 2026-04-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_ficha_cadastral_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipo_contrato',
            field=models.CharField(choices=[('mensal', 'Mensal'), ('quinzenal', 'Quinzenal'), ('projeto', 'Por Projeto'), ('avulso', 'Avulso / Sob demanda')], default='mensal', max_length=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='valor_mensal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fee mensal ou valor do projeto', max_digits=10, null=True),
        ),
    ]
