# Generated by Django 5.2.10 on 2026-04-06 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_tipo_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcofre',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Cliente vinculado (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cofre_itens', to='core.cliente'),
        ),
    ]
