# Generated by Django 5.2.10 on 2026-04-13 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_cliente_cofre'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastaEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cor', models.CharField(default='#f59e0b', help_text='Cor do ícone da pasta', max_length=7)),
                ('ordem', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pessoa')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastas_drive', to='core.empresa')),
                ('pasta_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subpastas', to='core.pastaempresa')),
            ],
            options={
                'verbose_name': 'Pasta da Empresa',
                'verbose_name_plural': 'Pastas das Empresas',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ArquivoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='drive/%Y/%m/')),
                ('nome_original', models.CharField(max_length=255)),
                ('tamanho', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pessoa')),
                ('pasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='core.pastaempresa')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
