# Generated by Django 5.2.10 on 2026-02-14 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplateGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada da tarefa')),
                ('processo', models.TextField(blank=True, help_text='Passo a passo de como executar')),
                ('recorrencia', models.CharField(choices=[('diaria', 'Diária'), ('semanal', 'Semanal'), ('quinzenal', 'Quinzenal'), ('mensal', 'Mensal'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='diaria', max_length=20)),
                ('dia_semana', models.IntegerField(blank=True, choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], help_text='Para tarefas semanais - qual dia da semana', null=True)),
                ('dia_mes', models.IntegerField(blank=True, help_text='Para tarefas mensais - qual dia do mês (1-31)', null=True)),
                ('dias_semana_ativos', models.CharField(default='0,1,2,3,4', help_text='Dias da semana ativos (0=Seg, 1=Ter, etc)', max_length=20)),
                ('ordem_execucao', models.IntegerField(default=0, help_text='Ordem na lista de rotina diária')),
                ('tempo_estimado', models.IntegerField(choices=[(0, 'Não definido'), (15, '15 minutos'), (30, '30 minutos'), (45, '45 minutos'), (60, '1 hora'), (90, '1h30'), (120, '2 horas'), (180, '3 horas'), (240, '4 horas')], default=0)),
                ('prioridade', models.IntegerField(choices=[(1, 'Baixa'), (2, 'Média'), (3, 'Alta')], default=1)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template Global',
                'verbose_name_plural': 'Templates Globais',
                'ordering': ['ordem_execucao', '-prioridade', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='SubTarefaTemplateGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('ordem', models.IntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtarefas', to='tenants.checklisttemplateglobal')),
            ],
            options={
                'verbose_name': 'Subtarefa do Template Global',
                'verbose_name_plural': 'Subtarefas do Template Global',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
