# Generated by Django 5.2.10 on 2026-02-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_add_global_checklist_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklisttemplateglobal',
            name='tenants',
            field=models.ManyToManyField(blank=True, help_text='Selecione os tenants que usarão este template', related_name='templates_globais', to='tenants.client'),
        ),
    ]
