# Generated by Django 5.2.10 on 2026-02-14 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_add_tenants_to_global_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtarefatemplateglobal',
            name='template',
        ),
        migrations.CreateModel(
            name='ProjetoTemplateGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('descricao', models.TextField(blank=True)),
                ('cor', models.CharField(default='#6366f1', help_text='Cor em hex', max_length=7)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tenants', models.ManyToManyField(blank=True, help_text='Selecione os tenants que poderão usar este template de projeto', related_name='templates_projeto_globais', to='tenants.client')),
            ],
            options={
                'verbose_name': 'Template de Projeto Global',
                'verbose_name_plural': 'Templates de Projeto Globais',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='EtapaTemplateGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('descricao', models.TextField(blank=True)),
                ('ordem', models.IntegerField(default=0)),
                ('tempo_estimado', models.IntegerField(blank=True, help_text='Tempo estimado em minutos', null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='tenants.projetotemplateglobal')),
            ],
            options={
                'verbose_name': 'Etapa do Template Global',
                'verbose_name_plural': 'Etapas do Template Global',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='ChecklistTemplateGlobal',
        ),
        migrations.DeleteModel(
            name='SubTarefaTemplateGlobal',
        ),
    ]
