"""
Data migration: Atualiza o Template Global "Implementação WhatsApp Business API"
com descrições explicativas detalhadas passo a passo em cada etapa.
"""
from django.db import migrations


ETAPAS_ATUALIZADAS = {
    1: {
        'titulo': 'Criar Conta Meta Business',
        'descricao': (
            'POR QUE ISSO É IMPORTANTE?\n'
            'A conta Meta Business é OBRIGATÓRIA para usar a API oficial do WhatsApp.\n'
            'Sem ela, você não consegue criar o App nem obter credenciais.\n'
            'A verificação empresarial desbloqueia recursos avançados e aumenta os limites de envio.\n\n'
            'COMO FAZER:\n\n'
            'PASSO 1: ACESSAR O META BUSINESS SUITE\n'
            '  Acesse: https://business.facebook.com\n'
            '  Se já tem conta Facebook pessoal, use ela para criar a conta Business.\n'
            '  Se não tem, crie uma conta Facebook primeiro.\n\n'
            'PASSO 2: CRIAR CONTA BUSINESS\n'
            '  Clique em "Criar conta" ou "Começar"\n'
            '  Preencha:\n'
            '  • Nome da empresa (como aparece nos documentos)\n'
            '  • Seu nome completo\n'
            '  • Email corporativo (evite @gmail, use @suaempresa.com.br)\n\n'
            'PASSO 3: VERIFICAR A EMPRESA\n'
            '  Vá em Configurações > Central de Segurança > Verificação de empresa\n'
            '  Documentos necessários:\n'
            '  • CNPJ (Cartão CNPJ da Receita Federal)\n'
            '  • Comprovante de endereço da empresa (conta de luz, água ou internet)\n'
            '  • Site da empresa (precisa ter domínio próprio)\n\n'
            '  Como baixar o Cartão CNPJ:\n'
            '  1. Acesse: https://servicos.receita.fazenda.gov.br/servicos/cnpjreva/cnpjreva_solicitacao.asp\n'
            '  2. Digite o CNPJ e resolva o captcha\n'
            '  3. Clique em "Emissão de Comprovante de Inscrição e de Situação Cadastral"\n'
            '  4. Salve como PDF\n\n'
            'PASSO 4: AGUARDAR APROVAÇÃO\n'
            '  A Meta analisa os documentos em 1-5 dias úteis.\n'
            '  Status possíveis:\n'
            '  • ✅ Verificada - Empresa aprovada, pode avançar\n'
            '  • ⏳ Em análise - Aguarde\n'
            '  • ❌ Rejeitada - Documentos incorretos, reenvie\n\n'
            'PROBLEMAS COMUNS:\n'
            '• "Nome da empresa não confere" → Use EXATAMENTE o nome que está no CNPJ\n'
            '• "Documentos rejeitados" → Envie o Cartão CNPJ oficial da Receita + conta recente\n'
            '• "Empresa já existe" → Alguém já criou conta com esse CNPJ, recupere o acesso\n'
            '• "Site não verificado" → Adicione o meta-tag no <head> do site ou DNS TXT record\n\n'
            'VALIDAÇÃO: Conta aprovada e status "Verificada" na Central de Segurança.'
        ),
        'tempo_estimado': 60,
    },
    2: {
        'titulo': 'Criar App no Meta Developers',
        'descricao': (
            'POR QUE ISSO É IMPORTANTE?\n'
            'O App é o "conector" entre seu sistema e o WhatsApp. Ele contém as credenciais\n'
            'de acesso (tokens) e é onde você configura webhooks e permissões.\n\n'
            'COMO FAZER:\n\n'
            'PASSO 1: ACESSAR O META DEVELOPERS\n'
            '  Acesse: https://developers.facebook.com\n'
            '  Faça login com a mesma conta da etapa anterior.\n'
            '  Se for primeira vez, aceite os termos de desenvolvedor.\n\n'
            'PASSO 2: CRIAR NOVO APP\n'
            '  Clique em "Meus Apps" (canto superior direito) > "Criar App"\n'
            '  Tipo de app: Selecione "Business" (Empresa)\n'
            '  Preencha:\n'
            '  • Nome do app: "NeuraxoCore WhatsApp" (ou nome da sua empresa)\n'
            '  • Email de contato: email@suaempresa.com.br\n'
            '  • Conta Business: Selecione a conta verificada na etapa anterior\n'
            '  Clique em "Criar app"\n\n'
            'PASSO 3: ADICIONAR PRODUTO WHATSAPP\n'
            '  Na tela do App, role até "Adicionar produtos ao app"\n'
            '  Encontre "WhatsApp" e clique em "Configurar"\n'
            '  O WhatsApp Business Platform será adicionado ao menu lateral.\n\n'
            'PASSO 4: CONFIGURAÇÃO INICIAL DO WHATSAPP\n'
            '  No menu lateral, clique em "WhatsApp" > "Primeiros Passos"\n'
            '  Você verá:\n'
            '  • Token de acesso temporário (expira em 24h - NÃO use em produção)\n'
            '  • Phone Number ID (número de teste da Meta)\n'
            '  • WhatsApp Business Account ID\n\n'
            '  ATENÇÃO: O token temporário é só para testes. Na etapa 4 vamos\n'
            '  gerar o token permanente.\n\n'
            'PASSO 5: VERIFICAR PERMISSÕES DO APP\n'
            '  Vá em App Settings > Advanced\n'
            '  Verifique que "App Type" está como "Business"\n'
            '  Vá em App Review > Permissions and Features\n'
            '  Solicite as permissões:\n'
            '  • whatsapp_business_messaging (enviar mensagens)\n'
            '  • whatsapp_business_management (gerenciar conta)\n\n'
            'PROBLEMAS COMUNS:\n'
            '• "WhatsApp não aparece nos produtos" → Verifique se o app é tipo Business\n'
            '• "Não consigo selecionar conta Business" → A conta precisa estar verificada\n'
            '• "Permissões negadas" → O App Review pode levar 1-3 dias para aprovar\n\n'
            'VALIDAÇÃO: App criado, WhatsApp Business API habilitado no menu lateral.'
        ),
        'tempo_estimado': 30,
    },
    3: {
        'titulo': 'Configurar Número de Telefone',
        'descricao': (
            'POR QUE ISSO É IMPORTANTE?\n'
            'Este é o número que seus clientes vão usar para conversar com sua empresa.\n'
            'Ele precisa ser um número real, verificado e exclusivo para a API.\n\n'
            'REQUISITOS DO NÚMERO:\n'
            '• Número que pode receber SMS ou ligação para verificação\n'
            '• NÃO pode estar registrado em nenhum WhatsApp (pessoal ou Business)\n'
            '• Se já está em uso no WhatsApp, precisa DESVINCULAR primeiro\n'
            '• Recomendado: usar chip exclusivo para a API\n\n'
            'COMO FAZER:\n\n'
            'PASSO 1: PREPARAR O NÚMERO\n'
            '  Se o número JÁ está no WhatsApp:\n'
            '  1. Abra o WhatsApp no celular com esse número\n'
            '  2. Vá em Configurações > Conta > Apagar conta\n'
            '  3. Confirme a exclusão\n'
            '  4. Aguarde 5 minutos\n\n'
            '  ATENÇÃO: Isso vai APAGAR todas as conversas do WhatsApp nesse número.\n'
            '  Faça backup antes se necessário!\n\n'
            '  Se quer manter o WhatsApp pessoal:\n'
            '  Compre um chip novo dedicado para a API da empresa.\n\n'
            'PASSO 2: ADICIONAR NO META DEVELOPERS\n'
            '  No painel do App, vá em WhatsApp > Configuração da API\n'
            '  Clique em "Adicionar número de telefone"\n'
            '  Preencha:\n'
            '  • Nome de exibição: Nome da empresa (ex: "Tarragona Store")\n'
            '  • Categoria: Escolha a mais adequada (ex: Shopping & Retail)\n'
            '  • Descrição: Breve descrição da empresa\n'
            '  • Número: +55 (DDD) XXXXXXXXX (formato internacional)\n\n'
            'PASSO 3: VERIFICAR O NÚMERO\n'
            '  Escolha o método de verificação:\n'
            '  • SMS (recomendado) - recebe código por mensagem de texto\n'
            '  • Ligação telefônica - recebe código por voz\n\n'
            '  Digite o código de 6 dígitos recebido.\n'
            '  Se não receber em 2 minutos, clique em "Reenviar código".\n\n'
            'PASSO 4: CONFIGURAR PERFIL COMERCIAL\n'
            '  Após verificar, configure o perfil:\n'
            '  • Foto de perfil (logo da empresa)\n'
            '  • Descrição (até 256 caracteres)\n'
            '  • Endereço\n'
            '  • Email\n'
            '  • Site\n'
            '  • Categoria do negócio\n\n'
            '  Isso aparece quando o cliente abre a conversa pela primeira vez.\n\n'
            'PASSO 5: ANOTAR IDENTIFICADORES\n'
            '  Após a verificação, anote:\n'
            '  • Phone Number ID: Identificador único do número (ex: 123456789012345)\n'
            '  • Display Phone Number: O número formatado (ex: +55 11 99999-9999)\n'
            '  Estes IDs serão usados nas chamadas de API.\n\n'
            'PROBLEMAS COMUNS:\n'
            '• "Número já registrado" → Desvinculue do WhatsApp primeiro (Passo 1)\n'
            '• "Código não chega" → Tente por ligação, verifique se o chip está ativo\n'
            '• "Nome rejeitado" → Não pode conter "WhatsApp", "Meta" ou "Facebook"\n'
            '• "Verificação falhou" → Aguarde 24h e tente novamente\n\n'
            'VALIDAÇÃO: Número verificado, status "Connected" no painel, Phone Number ID anotado.'
        ),
        'tempo_estimado': 30,
    },
    4: {
        'titulo': 'Obter Credenciais de Acesso',
        'descricao': (
            'POR QUE ISSO É IMPORTANTE?\n'
            'O token de acesso é a "senha" que autoriza seu sistema a enviar mensagens.\n'
            'O token temporário (24h) é só para testes. Para produção, você PRECISA de um\n'
            'token permanente via System User.\n\n'
            'COMO FAZER:\n\n'
            'PASSO 1: CRIAR SYSTEM USER\n'
            '  Acesse: https://business.facebook.com/settings/system-users\n'
            '  Clique em "Adicionar" (Add)\n'
            '  Preencha:\n'
            '  • Nome: "NeuraxoCore API" (ou nome do seu sistema)\n'
            '  • Função: Admin\n'
            '  Clique em "Criar usuário do sistema"\n\n'
            'PASSO 2: ATRIBUIR RECURSOS AO SYSTEM USER\n'
            '  Na lista de System Users, clique no que acabou de criar\n'
            '  Clique em "Atribuir recursos" (Assign Assets)\n'
            '  Selecione:\n'
            '  • Apps > [Seu App] > Controle total\n'
            '  • Contas do WhatsApp > [Sua conta] > Controle total\n'
            '  Clique em "Salvar alterações"\n\n'
            'PASSO 3: GERAR TOKEN PERMANENTE\n'
            '  Na página do System User, clique em "Gerar token" (Generate Token)\n'
            '  Selecione o App criado na etapa 2\n'
            '  Marque as permissões:\n'
            '  ☑ whatsapp_business_messaging\n'
            '  ☑ whatsapp_business_management\n'
            '  Clique em "Gerar token"\n\n'
            '  ⚠️ ATENÇÃO: O token só aparece UMA VEZ!\n'
            '  Copie e salve em local seguro IMEDIATAMENTE.\n'
            '  Se perder, terá que gerar um novo.\n\n'
            'PASSO 4: ANOTAR TODAS AS CREDENCIAIS\n'
            '  Salve em local seguro (gerenciador de senhas, .env):\n\n'
            '  WHATSAPP_TOKEN=EAAxxxxxxxxxxxxxxx (token permanente)\n'
            '  WHATSAPP_PHONE_ID=123456789012345 (da etapa 3)\n'
            '  WHATSAPP_BUSINESS_ID=987654321098765 (WhatsApp Business Account ID)\n'
            '  WHATSAPP_APP_ID=111222333444555 (ID do App)\n'
            '  WHATSAPP_APP_SECRET=abc123def456 (App Settings > Basic > App Secret)\n\n'
            '  Onde encontrar cada um:\n'
            '  • Token: gerado no Passo 3 acima\n'
            '  • Phone ID: WhatsApp > Configuração da API > Phone Number ID\n'
            '  • Business ID: WhatsApp > Configuração da API > WhatsApp Business Account ID\n'
            '  • App ID: App Settings > Basic > App ID\n'
            '  • App Secret: App Settings > Basic > App Secret (clique em "Show")\n\n'
            'PASSO 5: TESTAR O TOKEN\n'
            '  No terminal ou Postman, execute:\n'
            '  curl -X GET "https://graph.facebook.com/v21.0/{PHONE_ID}" \\\n'
            '    -H "Authorization: Bearer {TOKEN}"\n\n'
            '  Se retornar dados do número, o token está funcionando.\n'
            '  Se retornar erro 401/403, o token está incorreto ou expirado.\n\n'
            'SEGURANÇA:\n'
            '• NUNCA coloque o token no código-fonte (use .env ou variáveis de ambiente)\n'
            '• NUNCA compartilhe o token por email, chat ou mensagem\n'
            '• Rotacione o token a cada 6 meses\n'
            '• Se o token vazar, revogue IMEDIATAMENTE e gere um novo\n\n'
            'VALIDAÇÃO: Token permanente gerado, todos os IDs anotados, teste via curl OK.'
        ),
        'tempo_estimado': 30,
    },
    5: {
        'titulo': 'Testar Envio via API Explorer',
        'descricao': (
            'POR QUE ISSO É IMPORTANTE?\n'
            'Antes de integrar no código, teste pela ferramenta da Meta.\n'
            'Se funcionar aqui, você sabe que as credenciais estão corretas.\n'
            'Se falhar, o problema é nas credenciais, não no seu código.\n\n'
            'COMO FAZER:\n\n'
            'PASSO 1: ADICIONAR NÚMERO DE TESTE\n'
            '  No painel WhatsApp > Configuração da API > Enviar mensagem de teste\n'
            '  Em "Para", adicione um número para receber o teste:\n'
            '  • Use seu próprio WhatsApp pessoal\n'
            '  • Formato: +55 11 99999-9999\n'
            '  O número vai receber um código de verificação (confirme no celular).\n\n'
            'PASSO 2: ENVIAR MENSAGEM TEMPLATE\n'
            '  Na mesma tela, selecione:\n'
            '  • De: seu número Business (configurado na etapa 3)\n'
            '  • Para: número de teste adicionado\n'
            '  • Template: "hello_world" (template padrão da Meta)\n'
            '  Clique em "Enviar mensagem"\n\n'
            '  ✅ Se recebeu a mensagem no WhatsApp: credenciais OK!\n'
            '  ❌ Se não recebeu: verifique token e Phone Number ID.\n\n'
            'PASSO 3: TESTAR VIA CURL/POSTMAN\n'
            '  Para ter certeza que a API responde, teste diretamente:\n\n'
            '  curl -X POST "https://graph.facebook.com/v21.0/{PHONE_ID}/messages" \\\n'
            '    -H "Authorization: Bearer {TOKEN}" \\\n'
            '    -H "Content-Type: application/json" \\\n'
            '    -d \'{\n'
            '      "messaging_product": "whatsapp",\n'
            '      "to": "5511999999999",\n'
            '      "type": "template",\n'
            '      "template": {\n'
            '        "name": "hello_world",\n'
            '        "language": { "code": "en_US" }\n'
            '      }\n'
            '    }\'\n\n'
            '  Resposta esperada:\n'
            '  {"messaging_product": "whatsapp", "messages": [{"id": "wamid.xxx"}]}\n\n'
            '  Se retornou o ID da mensagem, está funcionando!\n\n'
            'PASSO 4: TESTAR ENVIO DE TEXTO SIMPLES\n'
            '  IMPORTANTE: Mensagens de texto livre só podem ser enviadas dentro da\n'
            '  "janela de 24h" - ou seja, DEPOIS que o cliente envia uma mensagem primeiro.\n'
            '  Para iniciar conversa, você PRECISA usar um template.\n\n'
            '  Para testar texto livre:\n'
            '  1. Envie uma mensagem DO seu WhatsApp pessoal PARA o número Business\n'
            '  2. Agora a janela de 24h está aberta\n'
            '  3. Envie via API:\n\n'
            '  curl -X POST "https://graph.facebook.com/v21.0/{PHONE_ID}/messages" \\\n'
            '    -H "Authorization: Bearer {TOKEN}" \\\n'
            '    -H "Content-Type: application/json" \\\n'
            '    -d \'{\n'
            '      "messaging_product": "whatsapp",\n'
            '      "to": "5511999999999",\n'
            '      "type": "text",\n'
            '      "text": { "body": "Teste de mensagem via API!" }\n'
            '    }\'\n\n'
            'PROBLEMAS COMUNS:\n'
            '• Erro 131030 "Number not on WhatsApp" → O número destino não tem WhatsApp\n'
            '• Erro 131047 "Re-engagement message" → Janela de 24h expirou, use template\n'
            '• Erro 100 "Invalid parameter" → Verifique formato do número (sem +, sem traços)\n'
            '• Erro 190 "Invalid OAuth access token" → Token expirado ou incorreto\n\n'
            'VALIDAÇÃO: Mensagem recebida no WhatsApp pessoal via API Explorer E via curl.'
        ),
        'tempo_estimado': 20,
    },
    6: {
        'titulo': 'Configurar Webhook',
        'descricao': (
            'POR QUE ISSO É IMPORTANTE?\n'
            'O webhook é como o WhatsApp avisa SEU sistema que algo aconteceu:\n'
            'mensagem recebida, mensagem entregue, mensagem lida, etc.\n'
            'Sem webhook, seu sistema envia mensagens mas não recebe nada de volta.\n\n'
            'COMO FUNCIONA:\n'
            '1. Cliente envia mensagem para seu número WhatsApp\n'
            '2. Meta recebe a mensagem\n'
            '3. Meta faz POST para a URL do seu webhook com os dados\n'
            '4. Seu sistema processa e responde\n\n'
            'COMO FAZER:\n\n'
            'PASSO 1: CRIAR ENDPOINT NO DJANGO\n'
            '  Você precisa de 2 views:\n\n'
            '  A) GET - Verificação do webhook (a Meta chama uma vez para validar)\n'
            '  O Meta envia: ?hub.mode=subscribe&hub.verify_token=SEU_TOKEN&hub.challenge=XXXX\n'
            '  Você deve retornar APENAS o valor de hub.challenge se o token conferir.\n\n'
            '  B) POST - Recebimento de eventos\n'
            '  O Meta envia um JSON com mensagens recebidas, status de entrega, etc.\n'
            '  Você processa e retorna HTTP 200.\n\n'
            '  Exemplo da view Django:\n'
            '  @csrf_exempt\n'
            '  def webhook_whatsapp(request):\n'
            '      if request.method == "GET":\n'
            '          token = request.GET.get("hub.verify_token")\n'
            '          challenge = request.GET.get("hub.challenge")\n'
            '          if token == settings.WHATSAPP_VERIFY_TOKEN:\n'
            '              return HttpResponse(challenge)\n'
            '          return HttpResponse("Forbidden", status=403)\n'
            '      elif request.method == "POST":\n'
            '          data = json.loads(request.body)\n'
            '          # Processar mensagens recebidas\n'
            '          processar_webhook(data)\n'
            '          return HttpResponse("OK", status=200)\n\n'
            'PASSO 2: EXPOR O ENDPOINT PUBLICAMENTE\n'
            '  O webhook PRECISA ser acessível pela internet com HTTPS.\n'
            '  Opções:\n'
            '  • Seu servidor já tem domínio + SSL → Use direto\n'
            '    URL: https://seudominio.com.br/api/webhook/whatsapp/\n'
            '  • Para desenvolvimento: Use ngrok (túnel temporário)\n'
            '    ngrok http 8000 → Gera URL https://xxxx.ngrok.io\n\n'
            'PASSO 3: CONFIGURAR NO META DEVELOPERS\n'
            '  No App, vá em WhatsApp > Configuração > Webhook\n'
            '  Clique em "Editar" (ou "Configurar")\n'
            '  Preencha:\n'
            '  • URL de callback: https://seudominio.com.br/api/webhook/whatsapp/\n'
            '  • Token de verificação: crie uma string secreta (ex: "meu_token_secreto_2026")\n'
            '    Salve esse mesmo token no .env como WHATSAPP_VERIFY_TOKEN\n'
            '  Clique em "Verificar e salvar"\n\n'
            '  A Meta vai fazer um GET para sua URL com o token.\n'
            '  Se seu endpoint responder corretamente, aparece ✅ "Webhook verificado".\n\n'
            'PASSO 4: ASSINAR CAMPOS DO WEBHOOK\n'
            '  Após verificar, clique em "Gerenciar" ao lado de Webhook\n'
            '  Marque os campos que quer receber:\n'
            '  ☑ messages - Mensagens recebidas (OBRIGATÓRIO)\n'
            '  ☑ messaging_handovers - Transferência de conversas\n'
            '  ☑ message_template_status_update - Aprovação de templates\n\n'
            'PASSO 5: TESTAR O WEBHOOK\n'
            '  1. Envie uma mensagem do seu WhatsApp pessoal para o número Business\n'
            '  2. Verifique nos logs do Django se o webhook foi acionado\n'
            '  3. O JSON recebido terá a estrutura:\n'
            '     {"object":"whatsapp_business_account","entry":[{"changes":[{"value":{"messages":[...]}}]}]}\n\n'
            'PROBLEMAS COMUNS:\n'
            '• "Verification failed" → Token no código diferente do informado na Meta\n'
            '• "URL not reachable" → Seu servidor não é acessível pela internet ou não tem HTTPS\n'
            '• "Webhook não recebe eventos" → Esqueceu de assinar os campos (Passo 4)\n'
            '• "CSRF error no Django" → Adicione @csrf_exempt na view do webhook\n\n'
            'VALIDAÇÃO: Webhook verificado com sucesso, mensagem enviada ao número Business\n'
            'aparece nos logs do sistema.'
        ),
        'tempo_estimado': 60,
    },
    7: {
        'titulo': 'Criar e Aprovar Templates de Mensagem',
        'descricao': (
            'POR QUE ISSO É IMPORTANTE?\n'
            'No WhatsApp Business API, você SÓ pode iniciar conversa usando templates\n'
            'aprovados pela Meta. Mensagens livres só funcionam dentro da janela de 24h\n'
            '(depois que o CLIENTE envia uma mensagem primeiro).\n\n'
            'TIPOS DE TEMPLATE:\n'
            '• MARKETING - Promoções, novidades, ofertas (mais restrito na aprovação)\n'
            '• UTILITY - Confirmações, atualizações, lembretes (aprovação mais fácil)\n'
            '• AUTHENTICATION - Códigos de verificação/OTP (aprovação automática)\n\n'
            'COMO FAZER:\n\n'
            'PASSO 1: ACESSAR O WHATSAPP MANAGER\n'
            '  Acesse: https://business.facebook.com/wa/manage/message-templates/\n'
            '  Ou: No App > WhatsApp > Gerenciar > Templates de mensagem\n\n'
            'PASSO 2: CRIAR TEMPLATES ESSENCIAIS\n'
            '  Clique em "Criar template"\n\n'
            '  TEMPLATE 1: LEMBRETE DE TAREFA (utility)\n'
            '  • Nome: lembrete_tarefa\n'
            '  • Categoria: Utility\n'
            '  • Idioma: Português (BR)\n'
            '  • Corpo: "Olá {{1}}! Você tem {{2}} tarefas pendentes para hoje.\n'
            '    Acesse o painel para verificar: {{3}}"\n'
            '  • Variáveis: {{1}}=nome, {{2}}=quantidade, {{3}}=link\n\n'
            '  TEMPLATE 2: ALERTA FINANCEIRO (utility)\n'
            '  • Nome: alerta_financeiro\n'
            '  • Categoria: Utility\n'
            '  • Corpo: "Atenção {{1}}! Você tem {{2}} contas a pagar vencendo\n'
            '    nos próximos dias. Acesse o financeiro para detalhes."\n\n'
            '  TEMPLATE 3: COBRANÇA DE FUNCIONÁRIO (utility)\n'
            '  • Nome: cobranca_tarefa\n'
            '  • Categoria: Utility\n'
            '  • Corpo: "Olá {{1}}, a tarefa \"{{2}}\" está atrasada desde {{3}}.\n'
            '    Por favor, atualize o status no sistema."\n\n'
            '  TEMPLATE 4: BEM-VINDO (marketing)\n'
            '  • Nome: boas_vindas\n'
            '  • Categoria: Marketing\n'
            '  • Corpo: "Bem-vindo(a) ao NeuraxoCore, {{1}}! 🎉\n'
            '    Seu painel está pronto. Acesse: {{2}}"\n\n'
            'PASSO 3: REGRAS PARA APROVAÇÃO\n'
            '  A Meta revisa cada template. Para ser aprovado:\n'
            '  ✅ Use linguagem clara e profissional\n'
            '  ✅ Inclua variáveis para personalização\n'
            '  ✅ Informe claramente quem é o remetente\n'
            '  ❌ NÃO use linguagem agressiva ou ameaçadora\n'
            '  ❌ NÃO envie conteúdo enganoso\n'
            '  ❌ NÃO inclua links encurtados (bit.ly, etc)\n'
            '  ❌ NÃO prometa ganhos financeiros\n\n'
            'PASSO 4: AGUARDAR APROVAÇÃO\n'
            '  A Meta analisa em minutos a horas (utility) ou 1-2 dias (marketing).\n'
            '  Status:\n'
            '  • APPROVED ✅ - Pode usar\n'
            '  • REJECTED ❌ - Ajuste e reenvie (veja o motivo da rejeição)\n'
            '  • PENDING ⏳ - Em análise\n\n'
            'PASSO 5: TESTAR TEMPLATE APROVADO\n'
            '  Use o API Explorer para enviar o template com variáveis preenchidas.\n'
            '  Verifique se a mensagem chega formatada corretamente.\n\n'
            'DICAS PARA APROVAÇÃO RÁPIDA:\n'
            '• Comece com templates Utility (aprovação mais fácil)\n'
            '• Use exemplos reais no campo "Sample" ao criar\n'
            '• Evite templates muito genéricos\n'
            '• Categoria errada = rejeição garantida\n\n'
            'VALIDAÇÃO: Pelo menos 3 templates com status APPROVED.'
        ),
        'tempo_estimado': 45,
    },
    8: {
        'titulo': 'Implementar Service de Envio',
        'descricao': (
            'POR QUE ISSO É IMPORTANTE?\n'
            'Este é o módulo do seu código que envia mensagens via API.\n'
            'Centralizar em um service facilita manutenção, logging e testes.\n\n'
            'COMO FAZER:\n\n'
            'PASSO 1: CRIAR O SERVICE\n'
            '  Crie um arquivo whatsapp_service.py com funções para cada tipo de envio.\n'
            '  O endpoint base é:\n'
            '  POST https://graph.facebook.com/v21.0/{PHONE_ID}/messages\n\n'
            '  Headers obrigatórios:\n'
            '  Authorization: Bearer {TOKEN}\n'
            '  Content-Type: application/json\n\n'
            'PASSO 2: IMPLEMENTAR FUNÇÕES\n\n'
            '  A) enviar_template(telefone, template_name, parametros)\n'
            '     Para iniciar conversas (fora da janela de 24h).\n'
            '     Body: {"messaging_product":"whatsapp","to":"5511...","type":"template",\n'
            '            "template":{"name":"xxx","language":{"code":"pt_BR"},\n'
            '            "components":[{"type":"body","parameters":[{"type":"text","text":"valor"}]}]}}\n\n'
            '  B) enviar_texto(telefone, mensagem)\n'
            '     Para respostas dentro da janela de 24h.\n'
            '     Body: {"messaging_product":"whatsapp","to":"5511...","type":"text",\n'
            '            "text":{"body":"Sua mensagem aqui"}}\n\n'
            '  C) enviar_midia(telefone, tipo, url_midia, caption)\n'
            '     Para enviar imagens, vídeos, áudios.\n'
            '     Tipos: image, video, audio, document\n'
            '     Body: {"messaging_product":"whatsapp","to":"5511...",\n'
            '            "type":"image","image":{"link":"https://url.jpg","caption":"Legenda"}}\n\n'
            '  D) enviar_botoes(telefone, texto, botoes)\n'
            '     Para mensagens interativas com botões.\n'
            '     Máximo 3 botões de resposta rápida.\n\n'
            'PASSO 3: TRATAMENTO DE RESPOSTAS\n'
            '  Sucesso (HTTP 200):\n'
            '  {"messaging_product":"whatsapp","messages":[{"id":"wamid.xxx"}]}\n'
            '  Salvar o wamid para rastrear status depois.\n\n'
            '  Erro:\n'
            '  {"error":{"message":"...","type":"OAuthException","code":100,"error_subcode":xxx}}\n'
            '  Logar o erro e tratar conforme o código.\n\n'
            'PASSO 4: CONFIGURAR VARIÁVEIS\n'
            '  No .env ou settings:\n'
            '  WHATSAPP_API_URL=https://graph.facebook.com/v21.0\n'
            '  WHATSAPP_TOKEN=EAAxxxxxx\n'
            '  WHATSAPP_PHONE_ID=123456789\n\n'
            'PASSO 5: TESTAR CADA FUNÇÃO\n'
            '  Via Django shell ou test:\n'
            '  from notifications.whatsapp_service import enviar_texto\n'
            '  resultado = enviar_texto("5511999999999", "Teste!")\n'
            '  print(resultado)\n\n'
            'BOAS PRÁTICAS:\n'
            '• Use requests.Session() para reutilizar conexões\n'
            '• Timeout de 30s nas requisições\n'
            '• Logar TODA requisição (sucesso e erro) para debug\n'
            '• Sanitizar números (remover +, espaços, traços)\n'
            '• Validar número antes de enviar (só dígitos, mín 10 chars)\n\n'
            'VALIDAÇÃO: Envio programático de template, texto e mídia funcionando via código.'
        ),
        'tempo_estimado': 120,
    },
    9: {
        'titulo': 'Implementar Recebimento de Mensagens',
        'descricao': (
            'POR QUE ISSO É IMPORTANTE?\n'
            'Para ter conversas bidirecionais, seu sistema precisa receber e processar\n'
            'as mensagens que os clientes enviam.\n\n'
            'COMO FAZER:\n\n'
            'PASSO 1: ENTENDER A ESTRUTURA DO WEBHOOK\n'
            '  Quando um cliente envia mensagem, a Meta posta este JSON:\n'
            '  {\n'
            '    "object": "whatsapp_business_account",\n'
            '    "entry": [{\n'
            '      "changes": [{\n'
            '        "value": {\n'
            '          "messaging_product": "whatsapp",\n'
            '          "metadata": {"phone_number_id": "xxx"},\n'
            '          "contacts": [{"profile":{"name":"João"}, "wa_id":"5511999..."}],\n'
            '          "messages": [{\n'
            '            "id": "wamid.xxx",\n'
            '            "from": "5511999999999",\n'
            '            "timestamp": "1234567890",\n'
            '            "type": "text",\n'
            '            "text": {"body": "Olá, preciso de ajuda"}\n'
            '          }]\n'
            '        }\n'
            '      }]\n'
            '    }]\n'
            '  }\n\n'
            'PASSO 2: PROCESSAR TIPOS DE MENSAGEM\n'
            '  O campo "type" indica o tipo. Implemente para cada um:\n\n'
            '  • text → msg["text"]["body"] = texto da mensagem\n'
            '  • image → msg["image"]["id"] = ID da mídia (precisa baixar via API)\n'
            '  • document → msg["document"]["id"] = ID + filename + mime_type\n'
            '  • audio → msg["audio"]["id"] = ID do áudio\n'
            '  • video → msg["video"]["id"] = ID do vídeo\n'
            '  • location → msg["location"]["latitude"], ["longitude"]\n'
            '  • interactive → msg["interactive"]["button_reply"]["id"] = resposta do botão\n'
            '  • reaction → msg["reaction"]["emoji"] = emoji de reação\n\n'
            'PASSO 3: BAIXAR MÍDIAS\n'
            '  Para mensagens com mídia, você precisa:\n'
            '  1. GET https://graph.facebook.com/v21.0/{media_id}\n'
            '     → Retorna {"url": "https://xxx"}\n'
            '  2. GET na URL retornada com Authorization: Bearer {TOKEN}\n'
            '     → Retorna o arquivo binário\n'
            '  3. Salvar no storage (media/ ou S3)\n\n'
            'PASSO 4: SALVAR NO BANCO\n'
            '  Crie um modelo para armazenar:\n'
            '  • telefone_remetente\n'
            '  • nome_remetente (vem em contacts[0].profile.name)\n'
            '  • tipo_mensagem (text, image, etc)\n'
            '  • conteudo (texto ou path do arquivo)\n'
            '  • wamid (ID único da mensagem)\n'
            '  • recebido_em (timestamp)\n\n'
            'PASSO 5: EVITAR DUPLICATAS\n'
            '  A Meta pode enviar o MESMO webhook mais de uma vez.\n'
            '  Use o wamid como chave única para ignorar duplicatas:\n'
            '  if MensagemRecebida.objects.filter(wamid=wamid).exists():\n'
            '      return  # Já processada\n\n'
            'PASSO 6: RESPONDER RAPIDAMENTE\n'
            '  O webhook da Meta tem timeout de 20 segundos.\n'
            '  Retorne HTTP 200 IMEDIATAMENTE e processe em background (Celery).\n'
            '  Se demorar mais de 20s, a Meta tenta reenviar e você perde eventos.\n\n'
            'VALIDAÇÃO: Enviar mensagem (texto e imagem) para o número Business e confirmar\n'
            'que aparece registrada no banco de dados do sistema.'
        ),
        'tempo_estimado': 120,
    },
    10: {
        'titulo': 'Implementar Status de Entrega',
        'descricao': (
            'POR QUE ISSO É IMPORTANTE?\n'
            'Saber se a mensagem foi entregue e lida é essencial para:\n'
            '• Confirmar que o cliente recebeu\n'
            '• Reenviar se falhou\n'
            '• Métricas de engajamento (taxa de leitura)\n\n'
            'COMO FUNCIONA:\n'
            'Quando você envia uma mensagem, o status evolui:\n'
            'sent → delivered → read\n'
            'Cada mudança gera um webhook.\n\n'
            'COMO FAZER:\n\n'
            'PASSO 1: ENTENDER O WEBHOOK DE STATUS\n'
            '  O JSON de status é diferente do de mensagem:\n'
            '  {\n'
            '    "entry": [{"changes": [{"value": {\n'
            '      "statuses": [{\n'
            '        "id": "wamid.xxx",\n'
            '        "status": "delivered",\n'
            '        "timestamp": "1234567890",\n'
            '        "recipient_id": "5511999999999"\n'
            '      }]\n'
            '    }}]}]\n'
            '  }\n\n'
            '  Status possíveis:\n'
            '  • sent - Mensagem enviada pela API (saiu do servidor)\n'
            '  • delivered - Entregue no celular do cliente (✓✓)\n'
            '  • read - Lida pelo cliente (✓✓ azul)\n'
            '  • failed - Falha no envio (ver campo "errors")\n\n'
            'PASSO 2: PROCESSAR NO WEBHOOK\n'
            '  No mesmo endpoint de webhook, verifique se é status:\n'
            '  if "statuses" in value:\n'
            '      for status in value["statuses"]:\n'
            '          atualizar_status_mensagem(\n'
            '              wamid=status["id"],\n'
            '              novo_status=status["status"],\n'
            '              timestamp=status["timestamp"]\n'
            '          )\n\n'
            'PASSO 3: ATUALIZAR NO BANCO\n'
            '  Atualize o registro da mensagem enviada:\n'
            '  msg = MensagemEnviada.objects.filter(wamid=wamid).first()\n'
            '  if msg:\n'
            '      msg.status = novo_status\n'
            '      msg.atualizado_em = timestamp\n'
            '      msg.save()\n\n'
            'PASSO 4: TRATAR FALHAS\n'
            '  Quando status = "failed", o JSON inclui detalhes:\n'
            '  "errors": [{"code": 131047, "title": "Re-engagement message"}]\n'
            '  Códigos comuns:\n'
            '  • 131047 - Janela de 24h expirou (use template)\n'
            '  • 131026 - Mensagem não entregue (cliente sem internet)\n'
            '  • 131053 - Número não é WhatsApp\n'
            '  • 130472 - Limite de mensagens atingido\n\n'
            'PASSO 5: TESTAR\n'
            '  1. Envie uma mensagem via API\n'
            '  2. Observe os webhooks chegando: sent → delivered\n'
            '  3. Abra o WhatsApp e leia a mensagem\n'
            '  4. Observe o webhook "read" chegando\n'
            '  5. Verifique no banco se todos os status foram atualizados\n\n'
            'VALIDAÇÃO: Enviar mensagem e acompanhar mudança de status em tempo real\n'
            '(sent → delivered → read) no banco de dados.'
        ),
        'tempo_estimado': 60,
    },
    11: {
        'titulo': 'Integrar Notificações do Sistema',
        'descricao': (
            'POR QUE ISSO É IMPORTANTE?\n'
            'Agora que o envio funciona, conecte aos eventos reais do NeuraxoCore.\n'
            'Assim o sistema envia WhatsApp automaticamente quando algo importante acontece.\n\n'
            'COMO FAZER:\n\n'
            'PASSO 1: MAPEAR EVENTOS → TEMPLATES\n'
            '  Defina qual template usar para cada evento:\n\n'
            '  EVENTO                          TEMPLATE              QUANDO\n'
            '  Tarefas do dia                  lembrete_tarefa       Todo dia no horário configurado\n'
            '  Tarefa atrasada                 cobranca_tarefa       Quando prazo vence\n'
            '  Nova demanda atribuída          nova_demanda          Ao criar demanda\n'
            '  Conta a pagar vencendo          alerta_financeiro     3 dias antes do vencimento\n'
            '  Dependência pendente            cobranca_dependencia  Diariamente até resolver\n'
            '  Resumo semanal                  resumo_semanal        Toda segunda-feira\n\n'
            'PASSO 2: IMPLEMENTAR DISPAROS\n'
            '  Para cada evento, crie uma task Celery que:\n'
            '  1. Busca os destinatários (quem deve receber)\n'
            '  2. Monta os parâmetros do template\n'
            '  3. Chama o service de envio\n'
            '  4. Registra no log de notificações\n\n'
            '  Exemplo:\n'
            '  @shared_task\n'
            '  def enviar_lembrete_diario():\n'
            '      for pessoa in Pessoa.objects.filter(receber_lembretes=True):\n'
            '          tarefas = ChecklistItem.objects.pendentes_hoje(pessoa)\n'
            '          if tarefas.exists():\n'
            '              enviar_template(\n'
            '                  pessoa.telefone_formatado(),\n'
            '                  "lembrete_tarefa",\n'
            '                  [pessoa.nome, str(tarefas.count()), URL_PAINEL]\n'
            '              )\n\n'
            'PASSO 3: AGENDAR COM CELERY BEAT\n'
            '  Configure os horários de disparo:\n'
            '  • Lembrete diário: todo dia às 08:00 (ou horário do usuário)\n'
            '  • Cobrança de atrasados: todo dia às 10:00\n'
            '  • Alerta financeiro: todo dia às 08:30\n'
            '  • Resumo semanal: segunda às 08:00\n\n'
            'PASSO 4: RESPEITAR PREFERÊNCIAS\n'
            '  Cada pessoa tem configuração de notificação:\n'
            '  • receber_lembretes: Sim/Não\n'
            '  • horario_lembrete: horário preferido\n'
            '  • empresas_lembrete_financeiro: quais empresas\n'
            '  Filtre SEMPRE pela preferência do usuário.\n\n'
            'PASSO 5: TESTAR CADA FLUXO\n'
            '  Para cada tipo de notificação:\n'
            '  1. Crie a situação (tarefa atrasada, conta vencendo, etc)\n'
            '  2. Dispare manualmente a task\n'
            '  3. Confirme recebimento no WhatsApp\n'
            '  4. Verifique o log de notificações\n\n'
            'VALIDAÇÃO: Cada tipo de evento (tarefas, demandas, financeiro) dispara\n'
            'notificação WhatsApp corretamente e aparece no log.'
        ),
        'tempo_estimado': 180,
    },
    12: {
        'titulo': 'Painel de Configuração por Tenant',
        'descricao': (
            'POR QUE ISSO É IMPORTANTE?\n'
            'Cada tenant (cliente) precisa poder configurar SUAS credenciais do WhatsApp.\n'
            'O admin do tenant não deve precisar de acesso ao código ou servidor.\n\n'
            'COMO FAZER:\n\n'
            'PASSO 1: CRIAR MODELO DE CONFIGURAÇÃO\n'
            '  No app do tenant, crie um model:\n'
            '  class ConfigWhatsApp(models.Model):\n'
            '      token = models.TextField(help_text="System User Token")\n'
            '      phone_id = models.CharField(max_length=50)\n'
            '      business_id = models.CharField(max_length=50)\n'
            '      verify_token = models.CharField(max_length=100)\n'
            '      ativo = models.BooleanField(default=False)\n'
            '      webhook_url = models.URLField(blank=True)\n'
            '  Use Singleton pattern (só 1 config por tenant).\n\n'
            'PASSO 2: CRIAR TELA DE CONFIGURAÇÃO\n'
            '  Tela simples no painel admin com:\n'
            '  • Campos para token, phone_id, business_id\n'
            '  • Botão "Testar Conexão" (chama a API e verifica)\n'
            '  • Botão "Enviar Mensagem de Teste"\n'
            '  • Toggle para ativar/desativar envios\n'
            '  • Lista de templates disponíveis (sincronizar da Meta)\n'
            '  • Configuração de horários de envio\n\n'
            'PASSO 3: ENCRIPTAR DADOS SENSÍVEIS\n'
            '  O token é um dado MUITO sensível. Encripte no banco:\n'
            '  • Use django-encrypted-model-fields ou fernet\n'
            '  • NUNCA exiba o token completo na tela (mascare: EAA...xxxx)\n'
            '  • Registre em log quem alterou as credenciais\n\n'
            'PASSO 4: TESTAR FLUXO COMPLETO\n'
            '  1. Login como admin de um tenant\n'
            '  2. Configurar credenciais na tela\n'
            '  3. Clicar "Testar Conexão" → deve retornar sucesso\n'
            '  4. Enviar mensagem de teste → deve receber no WhatsApp\n'
            '  5. Ativar envios automáticos\n\n'
            'VALIDAÇÃO: Admin do tenant consegue configurar credenciais, testar conexão\n'
            'e enviar mensagem de teste pelo painel, sem acesso ao código.'
        ),
        'tempo_estimado': 120,
    },
    13: {
        'titulo': 'Rate Limiting e Filas',
        'descricao': (
            'POR QUE ISSO É IMPORTANTE?\n'
            'A Meta tem limites rigorosos de envio. Se ultrapassar, seu número é bloqueado.\n'
            'Filas garantem que as mensagens sejam enviadas gradualmente, respeitando os limites.\n\n'
            'LIMITES DA META POR TIER:\n'
            '• Tier 1 (início): 1.000 conversas únicas/dia\n'
            '• Tier 2: 10.000 conversas/dia\n'
            '• Tier 3: 100.000 conversas/dia\n'
            '• Tier 4: ilimitado\n'
            'Tier sobe automaticamente conforme uso e quality rating.\n\n'
            'COMO FAZER:\n\n'
            'PASSO 1: CONFIGURAR CELERY + REDIS\n'
            '  Se ainda não tem:\n'
            '  • Instale Redis (broker de mensagens)\n'
            '  • Configure Celery no Django\n'
            '  • Crie tasks assíncronas para envio\n\n'
            'PASSO 2: IMPLEMENTAR FILA DE ENVIO\n'
            '  Em vez de enviar direto, enfileire:\n'
            '  # Não faça isso:\n'
            '  enviar_texto(telefone, msg)  # síncrono, bloqueia\n\n'
            '  # Faça isso:\n'
            '  enviar_texto.delay(telefone, msg)  # assíncrono, via Celery\n\n'
            'PASSO 3: IMPLEMENTAR RATE LIMITER\n'
            '  Controle a velocidade de envio:\n'
            '  • Máximo 80 mensagens por minuto (API limit = 80/min)\n'
            '  • Máximo X conversas por dia (baseado no tier)\n'
            '  • Intervalo mínimo entre mensagens para o MESMO número: 1 segundo\n\n'
            '  Use Redis para contadores:\n'
            '  chave = f"whatsapp:rate:{tenant_id}:{hoje}"\n'
            '  enviados_hoje = redis.incr(chave)\n'
            '  if enviados_hoje > LIMITE_DIARIO:\n'
            '      raise LimiteDiarioExcedido()\n\n'
            'PASSO 4: CONTROLE POR TENANT\n'
            '  Cada tenant tem seu próprio limite baseado no plano:\n'
            '  • Free: 100 msgs/dia\n'
            '  • Pro: 1.000 msgs/dia\n'
            '  • Enterprise: 10.000 msgs/dia\n\n'
            'PASSO 5: MONITORAR QUALITY RATING\n'
            '  A Meta avalia a qualidade do seu número:\n'
            '  • Green (Alta) → Pode aumentar tier\n'
            '  • Yellow (Média) → Atenção, melhorar\n'
            '  • Red (Baixa) → Risco de ter tier reduzido ou bloqueio\n\n'
            '  Quality cai quando:\n'
            '  • Clientes bloqueiam seu número\n'
            '  • Clientes reportam como spam\n'
            '  • Taxa de entrega está baixa\n\n'
            'PASSO 6: TESTAR\n'
            '  1. Enfileire 50 mensagens de uma vez\n'
            '  2. Verifique que são enviadas gradualmente (não todas de uma vez)\n'
            '  3. Verifique que o contador diário incrementa\n'
            '  4. Tente ultrapassar o limite e confirme que bloqueia\n\n'
            'VALIDAÇÃO: Enfileirar 50+ mensagens, confirmar envio respeitando rate limit\n'
            'e controle de limite diário por tenant.'
        ),
        'tempo_estimado': 120,
    },
    14: {
        'titulo': 'Histórico e Dashboard',
        'descricao': (
            'POR QUE ISSO É IMPORTANTE?\n'
            'O admin precisa ver o que foi enviado/recebido, acompanhar métricas\n'
            'e identificar problemas rapidamente.\n\n'
            'COMO FAZER:\n\n'
            'PASSO 1: TELA DE HISTÓRICO\n'
            '  Crie uma view com log de todas as mensagens:\n'
            '  • Lista com: data, telefone, tipo (enviada/recebida), conteúdo, status\n'
            '  • Filtros: por data, por status, por destinatário, por tipo\n'
            '  • Busca por texto no conteúdo\n'
            '  • Paginação (pode ter milhares de registros)\n'
            '  • Exportar para Excel/CSV\n\n'
            'PASSO 2: DASHBOARD DE MÉTRICAS\n'
            '  Cards com números principais:\n'
            '  • Mensagens enviadas hoje / esta semana / este mês\n'
            '  • Taxa de entrega (delivered / sent × 100)\n'
            '  • Taxa de leitura (read / delivered × 100)\n'
            '  • Taxa de falha (failed / sent × 100)\n'
            '  • Mensagens restantes hoje (limite - enviadas)\n\n'
            'PASSO 3: GRÁFICOS\n'
            '  • Gráfico de linha: Mensagens por dia (últimos 30 dias)\n'
            '  • Gráfico de pizza: Distribuição por tipo (template, texto, mídia)\n'
            '  • Gráfico de barras: Status (sent, delivered, read, failed)\n'
            '  • Gráfico de horários: Volume por hora do dia\n\n'
            'PASSO 4: ALERTAS NO DASHBOARD\n'
            '  Mostrar avisos quando:\n'
            '  • Taxa de falha > 5% (problema com números ou API)\n'
            '  • Limite diário atingindo 80% (pode ficar sem envios)\n'
            '  • Quality rating Yellow ou Red (risco de bloqueio)\n'
            '  • Token expirando (se usar token temporário)\n\n'
            'PASSO 5: CONVERSATION VIEW\n'
            '  Tela tipo chat mostrando a conversa completa com um número:\n'
            '  • Mensagens enviadas (lado direito, bolha azul)\n'
            '  • Mensagens recebidas (lado esquerdo, bolha cinza)\n'
            '  • Status de entrega (✓ ✓✓ ✓✓azul)\n'
            '  • Timestamps\n\n'
            'VALIDAÇÃO: Dashboard mostrando dados reais de mensagens enviadas/recebidas\n'
            'com filtros e gráficos funcionando.'
        ),
        'tempo_estimado': 180,
    },
    15: {
        'titulo': 'Tratamento de Erros e Retry',
        'descricao': (
            'POR QUE ISSO É IMPORTANTE?\n'
            'Falhas vão acontecer: timeout, rate limit, token expirado, número inválido.\n'
            'Um bom tratamento de erros garante que mensagens importantes não se percam.\n\n'
            'COMO FAZER:\n\n'
            'PASSO 1: CATEGORIZAR ERROS\n'
            '  TEMPORÁRIOS (vale retry):\n'
            '  • HTTP 429 - Rate limit (esperar e tentar novamente)\n'
            '  • HTTP 500/502/503 - Erro no servidor da Meta (tentar novamente)\n'
            '  • Timeout - Conexão lenta (tentar novamente)\n\n'
            '  PERMANENTES (NÃO dar retry):\n'
            '  • HTTP 400 - Dados inválidos (corrigir antes de reenviar)\n'
            '  • HTTP 401/403 - Token inválido (gerar novo token)\n'
            '  • Erro 131053 - Número não tem WhatsApp (remover da lista)\n'
            '  • Erro 131026 - Número bloqueou você (respeitar)\n\n'
            'PASSO 2: IMPLEMENTAR RETRY COM BACKOFF\n'
            '  Para erros temporários, retry com delay crescente:\n'
            '  @shared_task(bind=True, max_retries=3)\n'
            '  def enviar_mensagem_task(self, telefone, msg):\n'
            '      try:\n'
            '          enviar_texto(telefone, msg)\n'
            '      except RateLimitError:\n'
            '          self.retry(countdown=60)  # Espera 1 min\n'
            '      except TimeoutError:\n'
            '          self.retry(countdown=30)  # Espera 30s\n\n'
            '  Padrão de backoff:\n'
            '  • 1ª tentativa: imediata\n'
            '  • 2ª tentativa: após 30 segundos\n'
            '  • 3ª tentativa: após 2 minutos\n'
            '  • Desistir após 3 tentativas → marcar como FALHA\n\n'
            'PASSO 3: ALERTAR ADMIN EM FALHAS CRÍTICAS\n'
            '  Enviar alerta (email ou notificação no sistema) quando:\n'
            '  • Token expirado/inválido (TODAS as mensagens vão falhar)\n'
            '  • Número bloqueado pela Meta\n'
            '  • Quality rating mudou para Red\n'
            '  • Taxa de falha > 10% na última hora\n\n'
            'PASSO 4: DEAD LETTER QUEUE\n'
            '  Mensagens que falharam após todos os retries vão para uma "fila de mortos".\n'
            '  O admin pode:\n'
            '  • Ver quais mensagens falharam e por quê\n'
            '  • Retentar manualmente após corrigir o problema\n'
            '  • Descartar se não faz mais sentido enviar\n\n'
            'PASSO 5: MONITORAR SAÚDE DA INTEGRAÇÃO\n'
            '  Crie um health check que roda a cada 5 minutos:\n'
            '  • Verifica se o token está válido (GET /me)\n'
            '  • Verifica se o número está conectado\n'
            '  • Verifica taxa de erro recente\n'
            '  Se algo falhar, desativa envios automáticos e alerta admin.\n\n'
            'VALIDAÇÃO: Simular falhas (token errado, timeout) e confirmar retry automático.\n'
            'Confirmar que admin recebe alerta em falhas permanentes.'
        ),
        'tempo_estimado': 90,
    },
    16: {
        'titulo': 'Escalar Tier de Mensagens',
        'descricao': (
            'POR QUE ISSO É IMPORTANTE?\n'
            'Você começa no Tier 1 (1.000 conversas/dia). Para enviar mais,\n'
            'precisa escalar o tier mantendo boa qualidade.\n\n'
            'COMO FUNCIONA O SISTEMA DE TIERS:\n'
            '• Tier 1: 1.000 conversas únicas por dia\n'
            '• Tier 2: 10.000 conversas por dia\n'
            '• Tier 3: 100.000 conversas por dia\n'
            '• Tier 4: Ilimitado\n\n'
            'COMO SUBIR DE TIER:\n'
            'A Meta aumenta automaticamente quando:\n'
            '1. Você atinge 2x o limite atual em 7 dias consecutivos\n'
            '   Ex: Tier 1 (1K) → envie 500+ conversas/dia por 7 dias → Tier 2 (10K)\n'
            '2. Quality Rating está Green (alta qualidade)\n'
            '3. Número verificado e Business verificado\n\n'
            'COMO FAZER:\n\n'
            'PASSO 1: VERIFICAR TIER ATUAL\n'
            '  Meta Business Suite > WhatsApp > Visão geral\n'
            '  Ou: WhatsApp Manager > Phone Numbers > Messaging Limits\n\n'
            'PASSO 2: MANTER QUALITY RATING ALTO\n'
            '  O Quality Rating é o fator MAIS importante:\n\n'
            '  PARA MANTER GREEN:\n'
            '  ✅ Envie mensagens apenas para quem autorizou (opt-in)\n'
            '  ✅ Use templates relevantes e úteis\n'
            '  ✅ Responda rápido quando o cliente responde\n'
            '  ✅ Permita opt-out fácil ("digite SAIR para parar de receber")\n'
            '  ✅ Envie no horário comercial\n\n'
            '  EVITE:\n'
            '  ❌ Enviar para números que não te conhecem (spam)\n'
            '  ❌ Enviar muitos templates de marketing seguidos\n'
            '  ❌ Ignorar pedidos de parar de receber mensagens\n'
            '  ❌ Enviar madrugada/feriados\n'
            '  ❌ Usar linguagem agressiva ou enganosa\n\n'
            'PASSO 3: ESTRATÉGIA DE ESCALAÇÃO\n'
            '  Semana 1-2: Envie para lista pequena (funcionários, clientes fiéis)\n'
            '  Semana 3-4: Aumente gradualmente o volume\n'
            '  Mês 2: Se Quality Green, o tier deve subir automaticamente\n'
            '  Mês 3+: Continue aumentando gradualmente\n\n'
            'PASSO 4: SOLICITAR AUMENTO MANUAL (se necessário)\n'
            '  Se o tier não subiu automaticamente:\n'
            '  1. Acesse Meta Business Help Center\n'
            '  2. Solicite revisão do messaging limit\n'
            '  3. Apresente caso de uso legítimo\n\n'
            'O QUE DERRUBA O TIER:\n'
            '• Quality Rating Red por 7+ dias → Tier reduzido\n'
            '• Número reportado como spam muitas vezes → Pode ser bloqueado\n'
            '• Violação das políticas da Meta → Conta suspensa\n\n'
            'VALIDAÇÃO: Tier aumentado (verificar no painel Meta), Quality Rating Green.'
        ),
        'tempo_estimado': 30,
    },
    17: {
        'titulo': 'Testes Completos em Produção',
        'descricao': (
            'POR QUE ISSO É IMPORTANTE?\n'
            'Último checkpoint antes de considerar a integração como concluída.\n'
            'Teste TODOS os fluxos em produção com dados reais.\n\n'
            'COMO FAZER:\n\n'
            'CHECKLIST DE TESTES:\n\n'
            '══════════════════════════════════\n'
            'ENVIO DE MENSAGENS\n'
            '══════════════════════════════════\n'
            '☐ Enviar template com variáveis → Mensagem recebida corretamente\n'
            '☐ Enviar texto livre (dentro da janela 24h) → OK\n'
            '☐ Enviar imagem com legenda → Imagem e legenda aparecem\n'
            '☐ Enviar documento (PDF) → Download funciona\n'
            '☐ Enviar mensagem com botões → Botões clicáveis\n'
            '☐ Enviar fora da janela 24h sem template → Deve falhar (esperado)\n\n'
            '══════════════════════════════════\n'
            'RECEBIMENTO DE MENSAGENS\n'
            '══════════════════════════════════\n'
            '☐ Receber texto → Aparece no sistema\n'
            '☐ Receber imagem → Imagem salva e acessível\n'
            '☐ Receber áudio → Áudio salvo\n'
            '☐ Receber localização → Coordenadas registradas\n'
            '☐ Receber resposta de botão → Resposta identificada\n'
            '☐ Receber mensagem duplicada → Ignorada (sem duplicar)\n\n'
            '══════════════════════════════════\n'
            'STATUS DE ENTREGA\n'
            '══════════════════════════════════\n'
            '☐ Enviou → Status "sent" registrado\n'
            '☐ Entregou → Status "delivered" atualizado\n'
            '☐ Leu → Status "read" atualizado\n'
            '☐ Falhou → Status "failed" com motivo\n\n'
            '══════════════════════════════════\n'
            'NOTIFICAÇÕES DO SISTEMA\n'
            '══════════════════════════════════\n'
            '☐ Lembrete de tarefa diário → Recebido no horário\n'
            '☐ Cobrança de tarefa atrasada → Recebido corretamente\n'
            '☐ Alerta financeiro → Recebido com dados corretos\n'
            '☐ Nova demanda → Responsável notificado\n\n'
            '══════════════════════════════════\n'
            'MULTI-TENANT\n'
            '══════════════════════════════════\n'
            '☐ Tenant A envia → Usa credenciais do Tenant A\n'
            '☐ Tenant B envia → Usa credenciais do Tenant B\n'
            '☐ Mensagem do Tenant A NÃO aparece no Tenant B (isolamento)\n\n'
            '══════════════════════════════════\n'
            'RATE LIMITING E FILAS\n'
            '══════════════════════════════════\n'
            '☐ Enviar 50+ mensagens em lote → Enfileiradas e enviadas gradualmente\n'
            '☐ Atingir limite diário → Novas mensagens bloqueadas com aviso\n'
            '☐ Retry após falha temporária → Mensagem reenviada com sucesso\n\n'
            '══════════════════════════════════\n'
            'DASHBOARD E HISTÓRICO\n'
            '══════════════════════════════════\n'
            '☐ Histórico mostra todas as mensagens → Filtros funcionam\n'
            '☐ Métricas de entrega atualizadas → Números corretos\n'
            '☐ Gráficos renderizando → Dados reais\n\n'
            '══════════════════════════════════\n'
            'SEGURANÇA\n'
            '══════════════════════════════════\n'
            '☐ Token não exposto no frontend → Verificar network tab\n'
            '☐ Webhook valida assinatura → Rejeita requests falsos\n'
            '☐ Credenciais encriptadas no banco → Verificar via psql\n\n'
            '🎉 TUDO PASSANDO?\n'
            'Parabéns! A integração WhatsApp Business API está completa e\n'
            'funcionando em produção!\n\n'
            'MANUTENÇÃO CONTÍNUA:\n'
            '• Monitore Quality Rating semanalmente\n'
            '• Atualize a versão da API quando a Meta lançar nova (graph.facebook.com/vXX.0)\n'
            '• Revise templates trimestralmente\n'
            '• Rotacione tokens a cada 6 meses\n'
            '• Faça backup dos logs de mensagens\n\n'
            'VALIDAÇÃO: Todos os itens do checklist acima marcados como OK.'
        ),
        'tempo_estimado': 120,
    },
}


def atualizar_template(apps, schema_editor):
    EtapaTemplateGlobal = apps.get_model('tenants', 'EtapaTemplateGlobal')
    ProjetoTemplateGlobal = apps.get_model('tenants', 'ProjetoTemplateGlobal')

    template = ProjetoTemplateGlobal.objects.filter(
        titulo__icontains='WhatsApp Business API'
    ).first()

    if not template:
        return

    # Atualizar descrição do template
    template.descricao = (
        'Passo a passo completo para implementar a API oficial do WhatsApp Business '
        '(Cloud API da Meta). Cada etapa contém guia explicativo detalhado com '
        'instruções, exemplos de código, problemas comuns e validações.\n\n'
        'Tempo total estimado: ~22 horas de desenvolvimento\n'
        'Pré-requisitos: CNPJ verificado, número de telefone exclusivo, servidor com HTTPS.'
    )
    template.save()

    # Atualizar cada etapa
    for etapa in template.etapas.all():
        dados = ETAPAS_ATUALIZADAS.get(etapa.ordem)
        if dados:
            etapa.descricao = dados['descricao']
            etapa.tempo_estimado = dados.get('tempo_estimado')
            if 'titulo' in dados:
                etapa.titulo = dados['titulo']
            etapa.save()


def reverter(apps, schema_editor):
    # Não reverte - as descrições originais se perdem, mas o conteúdo é melhor
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_template_treinamento_agentes'),
    ]

    operations = [
        migrations.RunPython(atualizar_template, reverter),
    ]
