# Generated by Django 5.2.10 on 2026-03-29 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_acessocompartilhado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='admin_user',
            field=models.ForeignKey(blank=True, help_text='Usuário administrador principal deste tenant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants_admin', to=settings.AUTH_USER_MODEL, verbose_name='Administrador'),
        ),
    ]
