# Generated by Django 6.0.1 on 2026-01-28 22:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checklists', '0010_demanda_etapa_ordem_and_more'),
        ('core', '0002_empresa_remove_pessoa_workspaces_alter_cargo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaLancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10)),
                ('cor', models.CharField(default='#6b7280', max_length=7)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0)),
                ('empresa', models.ForeignKey(blank=True, help_text='Vazio = categoria global', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias_financeiro', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['tipo', 'ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10)),
                ('descricao', models.CharField(max_length=300)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='financeiro.categorialancamento')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_criados', to='core.pessoa')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to='core.empresa')),
                ('pessoa', models.ForeignKey(blank=True, help_text='Pessoa relacionada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='core.pessoa')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='checklists.projeto')),
            ],
            options={
                'verbose_name': 'Lançamento',
                'verbose_name_plural': 'Lançamentos',
                'ordering': ['-data', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='MetaEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(help_text='Mês (1-12)')),
                ('ano', models.IntegerField(help_text='Ano')),
                ('valor_meta', models.DecimalField(decimal_places=2, help_text='Meta mensal em R$', max_digits=12)),
                ('dias_uteis', models.IntegerField(default=22, help_text='Dias úteis no mês')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Metas',
                'ordering': ['-ano', '-mes'],
                'unique_together': {('empresa', 'mes', 'ano')},
            },
        ),
    ]
