# Generated by Django 6.0.1 on 2026-01-29 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_empresa_remove_pessoa_workspaces_alter_cargo_options_and_more'),
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='mp_payment_id',
            field=models.CharField(blank=True, help_text='ID do pagamento Mercado Pago (evita duplicação)', max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ConfigMercadoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(help_text='Access Token do Mercado Pago', max_length=200)),
                ('ativo', models.BooleanField(default=True)),
                ('ultima_sync', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_mp', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Config Mercado Pago',
                'verbose_name_plural': 'Configs Mercado Pago',
            },
        ),
    ]
