# Generated by Django 6.0.1 on 2026-01-29 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_empresa_remove_pessoa_workspaces_alter_cargo_options_and_more'),
        ('financeiro', '0002_lancamento_mp_payment_id_configmercadopago'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Bradesco PJ, Nubank, Inter', max_length=100)),
                ('banco', models.CharField(blank=True, help_text='Nome do banco', max_length=100)),
                ('tipo_conta', models.CharField(choices=[('corrente', 'Conta Corrente'), ('poupanca', 'Poupança'), ('pagamento', 'Conta de Pagamento'), ('investimento', 'Investimento')], default='corrente', max_length=20)),
                ('agencia', models.CharField(blank=True, max_length=20)),
                ('numero_conta', models.CharField(blank=True, max_length=30)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, help_text='Saldo no momento do cadastro', max_digits=12)),
                ('cor', models.CharField(default='#3b82f6', help_text='Cor para identificação', max_length=7)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_bancarias', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Conta Bancária',
                'verbose_name_plural': 'Contas Bancárias',
                'ordering': ['empresa', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='lancamento',
            name='conta',
            field=models.ForeignKey(blank=True, help_text='Conta bancária relacionada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='financeiro.contabancaria'),
        ),
    ]
