# Generated by Django 6.0.1 on 2026-01-29 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_contabancaria_lancamento_conta'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestacaoConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Ex: Marketing Facebook, Frete correios', max_length=300)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.categorialancamento')),
                ('lancamento', models.ForeignKey(help_text='Lançamento de retirada original', on_delete=django.db.models.deletion.CASCADE, related_name='prestacoes', to='financeiro.lancamento')),
            ],
            options={
                'verbose_name': 'Prestação de Conta',
                'verbose_name_plural': 'Prestações de Conta',
                'ordering': ['-criado_em'],
            },
        ),
    ]
