# Generated by Django 6.0.1 on 2026-01-29 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_empresa_remove_pessoa_workspaces_alter_cargo_options_and_more'),
        ('financeiro', '0004_prestacaoconta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Ex: Internet Vivo, Aluguel', max_length=300)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recorrencia', models.CharField(choices=[('mensal', 'Mensal'), ('semanal', 'Semanal'), ('quinzenal', 'Quinzenal')], default='mensal', max_length=10)),
                ('dia_vencimento', models.IntegerField(help_text='Dia do mês que vence (1-31)')),
                ('dia_execucao', models.CharField(choices=[('mesmo_dia', 'No dia do vencimento'), ('segunda', 'Toda Segunda'), ('terca', 'Toda Terça'), ('quarta', 'Toda Quarta'), ('quinta', 'Toda Quinta'), ('sexta', 'Toda Sexta'), ('sabado', 'Todo Sábado')], default='mesmo_dia', max_length=10)),
                ('ativo', models.BooleanField(default=True)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.categorialancamento')),
                ('conta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.contabancaria')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_pagar', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Conta a Pagar',
                'verbose_name_plural': 'Contas a Pagar',
                'ordering': ['empresa', 'descricao'],
            },
        ),
        migrations.CreateModel(
            name='ContaPagarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_vencimento', models.DateField()),
                ('data_execucao', models.DateField(help_text='Dia que deve aparecer na rotina')),
                ('pago', models.BooleanField(default=False)),
                ('pago_em', models.DateTimeField(blank=True, null=True)),
                ('conta_pagar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='financeiro.contapagar')),
                ('lancamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conta_pagar_item', to='financeiro.lancamento')),
            ],
            options={
                'verbose_name': 'Item Conta a Pagar',
                'verbose_name_plural': 'Itens Contas a Pagar',
                'ordering': ['data_vencimento'],
                'unique_together': {('conta_pagar', 'mes', 'ano')},
            },
        ),
    ]
