# Generated by Django 5.2.10 on 2026-02-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_contapagar_contapagaritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='dia_execucao_mensal',
            field=models.IntegerField(blank=True, help_text='Dia do mês para execução (1-31)', null=True),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='dia_execucao',
            field=models.CharField(choices=[('mesmo_dia', 'No dia do vencimento'), ('dia_mes', 'Dia específico do mês'), ('segunda', 'Toda Segunda'), ('terca', 'Toda Terça'), ('quarta', 'Toda Quarta'), ('quinta', 'Toda Quinta'), ('sexta', 'Toda Sexta'), ('sabado', 'Todo Sábado')], default='mesmo_dia', max_length=10),
        ),
    ]
