# Generated by Django 5.2.10 on 2026-02-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0006_add_dia_execucao_mensal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contapagar',
            name='recorrencia',
            field=models.CharField(choices=[('mensal', 'Mensal'), ('semanal', 'Semanal'), ('quinzenal', 'Quinzenal'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='mensal', max_length=12),
        ),
    ]
