# Generated by Django 5.2.10 on 2026-02-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0007_add_recorrencias_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='data_inicio',
            field=models.DateField(blank=True, help_text='Data do primeiro vencimento (para contas futuras)', null=True),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='recorrencia',
            field=models.CharField(choices=[('unica', 'Única (sem recorrência)'), ('mensal', 'Mensal'), ('semanal', 'Semanal'), ('quinzenal', 'Quinzenal'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='mensal', max_length=12),
        ),
    ]
