# Generated by Django 5.2.10 on 2026-02-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0008_add_data_inicio_conta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contapagar',
            name='data_inicio',
        ),
        migrations.AddField(
            model_name='contapagar',
            name='data_vencimento',
            field=models.DateField(blank=True, help_text='Data do primeiro vencimento', null=True),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='dia_vencimento',
            field=models.IntegerField(default=1, help_text='Dia do mês que vence (1-31)'),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='recorrencia',
            field=models.CharField(choices=[('unica', 'Única (sem recorrência)'), ('diaria', 'Diária'), ('semanal', 'Semanal'), ('quinzenal', 'Quinzenal'), ('mensal', 'Mensal'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='mensal', max_length=12),
        ),
    ]
