# Generated by Django 5.2.10 on 2026-02-08 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0016_add_mapa_mental'),
        ('core', '0006_add_cliente'),
        ('financeiro', '0010_add_parcelamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contapagar',
            name='valor',
            field=models.DecimalField(decimal_places=2, help_text='Valor total (ou da parcela se parcelado)', max_digits=12),
        ),
        migrations.CreateModel(
            name='ContaReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Ex: Mensalidade, Projeto X, Consultoria', max_length=300)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor total (ou da parcela se parcelado)', max_digits=12)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, help_text='Valor total do contrato (quando parcelado)', max_digits=12, null=True)),
                ('parcelado', models.BooleanField(default=False, help_text='Se é um recebimento parcelado')),
                ('total_parcelas', models.IntegerField(default=1, help_text='Número total de parcelas')),
                ('recorrencia', models.CharField(choices=[('unica', 'Única (sem recorrência)'), ('parcelada', 'Parcelada'), ('semanal', 'Semanal'), ('quinzenal', 'Quinzenal'), ('mensal', 'Mensal'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='mensal', max_length=12)),
                ('data_vencimento', models.DateField(blank=True, help_text='Data do primeiro vencimento', null=True)),
                ('dia_vencimento', models.IntegerField(default=1, help_text='Dia do mês que vence (1-31)')),
                ('notificar_cliente', models.BooleanField(default=False, help_text='Enviar lembrete ao cliente')),
                ('dias_antecedencia', models.IntegerField(default=3, help_text='Dias antes do vencimento para notificar')),
                ('ativo', models.BooleanField(default=True)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.categorialancamento')),
                ('cliente', models.ForeignKey(blank=True, help_text='Cliente devedor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_receber', to='core.pessoa')),
                ('conta', models.ForeignKey(blank=True, help_text='Conta onde será recebido', null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.contabancaria')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_receber', to='core.empresa')),
                ('projeto', models.ForeignKey(blank=True, help_text='Projeto relacionado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_receber', to='checklists.projeto')),
            ],
            options={
                'verbose_name': 'Conta a Receber',
                'verbose_name_plural': 'Contas a Receber',
                'ordering': ['empresa', 'descricao'],
            },
        ),
        migrations.CreateModel(
            name='ContaReceberItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_vencimento', models.DateField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('recebido', 'Recebido'), ('atrasado', 'Atrasado'), ('cancelado', 'Cancelado')], default='pendente', max_length=12)),
                ('recebido', models.BooleanField(default=False)),
                ('recebido_em', models.DateTimeField(blank=True, null=True)),
                ('valor_recebido', models.DecimalField(blank=True, decimal_places=2, help_text='Valor efetivamente recebido (pode ser diferente do esperado)', max_digits=12, null=True)),
                ('parcela_numero', models.IntegerField(blank=True, help_text='Número da parcela (1, 2, 3...)', null=True)),
                ('notificado', models.BooleanField(default=False)),
                ('notificado_em', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('conta_receber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='financeiro.contareceber')),
                ('lancamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conta_receber_item', to='financeiro.lancamento')),
            ],
            options={
                'verbose_name': 'Item Conta a Receber',
                'verbose_name_plural': 'Itens Contas a Receber',
                'ordering': ['data_vencimento'],
            },
        ),
    ]
