# Generated by Django 5.2.10 on 2026-02-08 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_cliente'),
        ('financeiro', '0011_add_contas_receber'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('conta_pagar_vencendo', 'Conta a Pagar Vencendo'), ('conta_pagar_atrasada', 'Conta a Pagar Atrasada'), ('conta_receber_vencendo', 'Conta a Receber Vencendo'), ('conta_receber_atrasada', 'Conta a Receber Atrasada'), ('meta_diaria', 'Meta Diaria Nao Atingida'), ('saldo_baixo', 'Saldo Baixo em Conta')], max_length=30)),
                ('ativo', models.BooleanField(default=True)),
                ('dias_antecedencia', models.IntegerField(default=3, help_text='Dias antes do vencimento para alertar')),
                ('valor_limite', models.DecimalField(blank=True, decimal_places=2, help_text='Valor limite para alerta de saldo baixo', max_digits=12, null=True)),
                ('notificar_whatsapp', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('destinatarios', models.ManyToManyField(blank=True, help_text='Pessoas que receberao o alerta', related_name='alertas_financeiros', to='core.pessoa')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_financeiros', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Alerta Financeiro',
                'verbose_name_plural': 'Alertas Financeiros',
                'ordering': ['empresa', 'tipo'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('sucesso', models.BooleanField(default=True)),
                ('erro', models.TextField(blank=True)),
                ('alerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='financeiro.alertafinanceiro')),
                ('conta_pagar_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.contapagaritem')),
                ('conta_receber_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.contareceberitem')),
                ('enviado_para', models.ManyToManyField(blank=True, related_name='alertas_recebidos', to='core.pessoa')),
            ],
            options={
                'verbose_name': 'Historico de Alerta',
                'verbose_name_plural': 'Historico de Alertas',
                'ordering': ['-enviado_em'],
            },
        ),
    ]
