# Generated by Django 5.2.10 on 2026-02-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0012_add_alertas_financeiros'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='valor_estimado',
            field=models.BooleanField(default=False, help_text='Valor aproximado/desconhecido no momento do cadastro'),
        ),
        migrations.AddField(
            model_name='contapagaritem',
            name='dispensado',
            field=models.BooleanField(default=False, help_text='Dispensado sem pagamento'),
        ),
        migrations.AddField(
            model_name='contapagaritem',
            name='dispensado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
