# Generated by Django 5.2.10 on 2026-04-06 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_tipo_contrato'),
        ('financeiro', '0013_add_valor_estimado_dispensado'),
    ]

    operations = [
        migrations.AddField(
            model_name='contareceber',
            name='cliente_empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa-cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_receber', to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Pessoa (legado)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_receber', to='core.pessoa'),
        ),
    ]
