# Generated by Django 5.2.10 on 2026-04-12 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_cliente_cofre'),
        ('financeiro', '0014_add_cliente_empresa_conta_receber'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatewayPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('mercadopago', 'Mercado Pago'), ('asaas', 'Asaas'), ('efi', 'EFI (Gerencianet)')], max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('ativo', 'Ativo'), ('erro', 'Erro de Conexão'), ('desconectado', 'Desconectado')], default='pendente', max_length=20)),
                ('credentials_encrypted', models.TextField(blank=True, help_text='JSON criptografado com credenciais')),
                ('sandbox', models.BooleanField(default=False, help_text='Usar ambiente sandbox/homologação')),
                ('ultima_sync', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gateway_pagamento', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Gateway de Pagamento',
                'verbose_name_plural': 'Gateways de Pagamento',
            },
        ),
    ]
