# Generated by Django 6.0.1 on 2026-01-27 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada da tarefa')),
                ('processo', models.TextField(blank=True, help_text='Passo a passo de como executar')),
                ('recorrencia', models.CharField(choices=[('diaria', 'Diária'), ('semanal', 'Semanal'), ('quinzenal', 'Quinzenal'), ('mensal', 'Mensal'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='diaria', max_length=20)),
                ('dia_semana', models.IntegerField(blank=True, choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], help_text='Para tarefas semanais - qual dia da semana', null=True)),
                ('dia_mes', models.IntegerField(blank=True, help_text='Para tarefas mensais - qual dia do mês (1-31)', null=True)),
                ('prioridade', models.IntegerField(choices=[(1, 'Baixa'), (2, 'Média'), (3, 'Alta')], default=1)),
                ('ativo', models.BooleanField(default=True)),
                ('enviar_lembrete', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cargo_responsavel', models.ForeignKey(blank=True, help_text='Ou atribuir a todos do cargo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists', to='core.cargo')),
                ('responsavel', models.ForeignKey(blank=True, help_text='Pessoa específica responsável', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists_responsavel', to='core.pessoa')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='core.workspace')),
            ],
            options={
                'verbose_name': 'Template de Checklist',
                'verbose_name_plural': 'Templates de Checklist',
                'ordering': ['workspace', '-prioridade', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_referencia', models.DateField(help_text='Data de referência desta tarefa')),
                ('data_limite', models.DateTimeField(help_text='Prazo para conclusão')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('atrasado', 'Atrasado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, help_text='Observações do responsável')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('lembrete_enviado', models.BooleanField(default=False)),
                ('cobranca_enviada', models.BooleanField(default=False)),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_items', to='core.pessoa')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checklists.checklisttemplate')),
            ],
            options={
                'verbose_name': 'Item de Checklist',
                'verbose_name_plural': 'Itens de Checklist',
                'ordering': ['-data_referencia', '-data_limite'],
                'unique_together': {('template', 'responsavel', 'data_referencia')},
            },
        ),
    ]
