# Generated by Django 6.0.1 on 2026-01-28 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='anotacoes',
            field=models.TextField(blank=True, help_text='Anotações durante a execução'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='timer_acumulado',
            field=models.IntegerField(default=0, help_text='Tempo acumulado em segundos'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='timer_ativo',
            field=models.BooleanField(default=False, help_text='Se o timer está rodando'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='timer_inicio',
            field=models.DateTimeField(blank=True, help_text='Quando o timer foi iniciado', null=True),
        ),
        migrations.CreateModel(
            name='SubTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('concluida', models.BooleanField(default=False)),
                ('ordem', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtarefas', to='checklists.checklistitem')),
            ],
            options={
                'verbose_name': 'Subtarefa',
                'verbose_name_plural': 'Subtarefas',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
