# Generated by Django 6.0.1 on 2026-01-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0002_checklistitem_anotacoes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='iniciado_em',
            field=models.DateTimeField(blank=True, help_text='Quando a tarefa foi iniciada pela primeira vez', null=True),
        ),
    ]
