# Generated by Django 6.0.1 on 2026-01-28 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0003_checklistitem_iniciado_em'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='dependencia_resolvida_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='dependente_de',
            field=models.ForeignKey(blank=True, help_text='Pessoa de quem esta tarefa depende', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_dependentes', to='core.pessoa'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='motivo_dependencia',
            field=models.CharField(blank=True, help_text='Motivo da dependência (ex: Aguardando aprovação do João)', max_length=500),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('dependente', 'Aguardando Dependência'), ('concluido', 'Concluído'), ('atrasado', 'Atrasado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20),
        ),
    ]
