# Generated by Django 6.0.1 on 2026-01-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0004_checklistitem_dependencia_resolvida_em_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoDemanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='demandas/anexos/%Y/%m/')),
                ('nome_original', models.CharField(max_length=255)),
                ('tamanho', models.IntegerField(default=0, help_text='Tamanho em bytes')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Anexo',
                'verbose_name_plural': 'Anexos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioDemanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('descricao', models.TextField(blank=True, help_text='Detalhes da demanda')),
                ('instrucoes', models.TextField(blank=True, help_text='Instruções de como executar')),
                ('prazo', models.DateTimeField(help_text='Data e hora limite para conclusão')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('dependente', 'Aguardando Dependência'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('anotacoes', models.TextField(blank=True, help_text='Anotações do responsável durante execução')),
                ('motivo_dependencia', models.CharField(blank=True, max_length=500)),
                ('dependencia_resolvida_em', models.DateTimeField(blank=True, null=True)),
                ('iniciado_em', models.DateTimeField(blank=True, null=True)),
                ('timer_inicio', models.DateTimeField(blank=True, null=True)),
                ('timer_acumulado', models.IntegerField(default=0, help_text='Tempo em segundos')),
                ('timer_ativo', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Demanda',
                'verbose_name_plural': 'Demandas',
                'ordering': ['-prioridade', 'prazo', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='SubTarefaDemanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('concluida', models.BooleanField(default=False)),
                ('ordem', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Subtarefa de Demanda',
                'verbose_name_plural': 'Subtarefas de Demanda',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='checklistitem',
            options={'ordering': ['ordem', '-data_referencia', 'template__prioridade'], 'verbose_name': 'Item de Checklist', 'verbose_name_plural': 'Itens de Checklist'},
        ),
        migrations.AlterModelOptions(
            name='checklisttemplate',
            options={'ordering': ['ordem_execucao', '-prioridade', 'titulo'], 'verbose_name': 'Rotina Diária', 'verbose_name_plural': 'Rotinas Diárias'},
        ),
        migrations.RemoveField(
            model_name='checklisttemplate',
            name='workspace',
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='ordem',
            field=models.IntegerField(default=0, help_text='Ordem de execução na rotina do dia'),
        ),
    ]
