# Generated by Django 6.0.1 on 2026-01-28 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0005_anexodemanda_comentariodemanda_demanda_and_more'),
        ('core', '0002_empresa_remove_pessoa_workspaces_alter_cargo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklisttemplate',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='ordem_execucao',
            field=models.IntegerField(default=0, help_text='Ordem na lista de rotina diária (menor = primeiro)'),
        ),
        migrations.AddField(
            model_name='anexodemanda',
            name='enviado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pessoa'),
        ),
        migrations.AddField(
            model_name='comentariodemanda',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pessoa'),
        ),
        migrations.AddField(
            model_name='demanda',
            name='dependente_de',
            field=models.ForeignKey(blank=True, help_text='Pessoa de quem esta demanda depende', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandas_dependentes', to='core.pessoa'),
        ),
        migrations.AddField(
            model_name='demanda',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandas', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='demanda',
            name='responsavel',
            field=models.ForeignKey(help_text='Funcionário responsável por executar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandas_recebidas', to='core.pessoa'),
        ),
        migrations.AddField(
            model_name='demanda',
            name='solicitante',
            field=models.ForeignKey(help_text='Gestor que criou a demanda', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandas_criadas', to='core.pessoa'),
        ),
        migrations.AddField(
            model_name='comentariodemanda',
            name='demanda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='checklists.demanda'),
        ),
        migrations.AddField(
            model_name='anexodemanda',
            name='demanda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='checklists.demanda'),
        ),
        migrations.AddField(
            model_name='subtarefademanda',
            name='demanda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtarefas_demanda', to='checklists.demanda'),
        ),
    ]
