# Generated by Django 6.0.1 on 2026-01-28 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0006_checklisttemplate_empresa_and_more'),
        ('core', '0002_empresa_remove_pessoa_workspaces_alter_cargo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='dia_fechado',
            field=models.BooleanField(default=False, help_text='Se o dia foi fechado para esta tarefa'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='justificativa',
            field=models.TextField(blank=True, help_text='Motivo por não ter concluído a tarefa'),
        ),
        migrations.CreateModel(
            name='AproveitamentoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('total_tarefas', models.IntegerField(default=0)),
                ('tarefas_concluidas', models.IntegerField(default=0)),
                ('tarefas_nao_concluidas', models.IntegerField(default=0)),
                ('percentual', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tempo_total_segundos', models.IntegerField(default=0, help_text='Tempo total trabalhado em segundos')),
                ('fechado_em', models.DateTimeField(blank=True, help_text='Quando o dia foi fechado', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aproveitamentos', to='core.pessoa')),
            ],
            options={
                'verbose_name': 'Aproveitamento Diário',
                'verbose_name_plural': 'Aproveitamentos Diários',
                'ordering': ['-data'],
                'unique_together': {('pessoa', 'data')},
            },
        ),
        migrations.CreateModel(
            name='TarefaNaoConcluida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificativa', models.TextField(help_text='Motivo por não ter concluído')),
                ('registrado_em', models.DateTimeField(auto_now_add=True)),
                ('aproveitamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_nao_concluidas_detalhe', to='checklists.aproveitamentodiario')),
                ('checklist_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registro_nao_concluida', to='checklists.checklistitem')),
            ],
            options={
                'verbose_name': 'Tarefa Não Concluída',
                'verbose_name_plural': 'Tarefas Não Concluídas',
            },
        ),
    ]
