# Generated by Django 6.0.1 on 2026-01-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0007_checklistitem_dia_fechado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='dependente_externo',
            field=models.CharField(blank=True, help_text='Nome de pessoa externa (não cadastrada no sistema)', max_length=200),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='telefone_dependente_externo',
            field=models.CharField(blank=True, help_text='WhatsApp da pessoa externa', max_length=20),
        ),
        migrations.AddField(
            model_name='demanda',
            name='dependente_externo',
            field=models.CharField(blank=True, help_text='Nome de pessoa externa (não cadastrada no sistema)', max_length=200),
        ),
        migrations.AddField(
            model_name='demanda',
            name='telefone_dependente_externo',
            field=models.CharField(blank=True, help_text='WhatsApp da pessoa externa', max_length=20),
        ),
    ]
