# Generated by Django 6.0.1 on 2026-01-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0008_checklistitem_dependente_externo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklisttemplate',
            name='tempo_estimado',
            field=models.IntegerField(choices=[(0, 'Não definido'), (15, '15 minutos'), (30, '30 minutos'), (45, '45 minutos'), (60, '1 hora'), (90, '1h30'), (120, '2 horas'), (180, '3 horas'), (240, '4 horas'), (480, '1 dia'), (960, '2 dias'), (1440, '3 dias')], default=0, help_text='Tempo máximo estimado para conclusão'),
        ),
        migrations.AddField(
            model_name='demanda',
            name='tempo_estimado',
            field=models.IntegerField(choices=[(0, 'Não definido'), (15, '15 minutos'), (30, '30 minutos'), (45, '45 minutos'), (60, '1 hora'), (90, '1h30'), (120, '2 horas'), (180, '3 horas'), (240, '4 horas'), (480, '1 dia'), (960, '2 dias'), (1440, '3 dias')], default=0, help_text='Tempo máximo estimado para conclusão'),
        ),
    ]
