# Generated by Django 6.0.1 on 2026-01-28 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0009_checklisttemplate_tempo_estimado_and_more'),
        ('core', '0002_empresa_remove_pessoa_workspaces_alter_cargo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanda',
            name='etapa_ordem',
            field=models.IntegerField(default=0, help_text='Ordem da etapa dentro do projeto'),
        ),
        migrations.AlterField(
            model_name='checklisttemplate',
            name='tempo_estimado',
            field=models.IntegerField(choices=[(0, 'Não definido'), (15, '15 minutos'), (30, '30 minutos'), (45, '45 minutos'), (60, '1 hora'), (90, '1h30'), (120, '2 horas'), (180, '3 horas'), (240, '4 horas')], default=0, help_text='Tempo máximo estimado para conclusão'),
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('descricao', models.TextField(blank=True)),
                ('prazo', models.DateField(blank=True, help_text='Prazo geral do projeto', null=True)),
                ('status', models.CharField(choices=[('planejamento', 'Planejamento'), ('em_andamento', 'Em Andamento'), ('pausado', 'Pausado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='planejamento', max_length=20)),
                ('cor', models.CharField(default='#6366f1', help_text='Cor visual do projeto (hex)', max_length=7)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='core.empresa')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_lider', to='core.pessoa')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.AddField(
            model_name='demanda',
            name='projeto',
            field=models.ForeignKey(blank=True, help_text='Projeto ao qual esta demanda pertence', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandas', to='checklists.projeto'),
        ),
    ]
