# Generated by Django 6.0.1 on 2026-01-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0010_demanda_etapa_ordem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='cancelamento_motivo',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='cancelamento_solicitado',
            field=models.BooleanField(default=False, help_text='Funcionário solicitou cancelamento'),
        ),
    ]
