# Generated by Django 6.0.1 on 2026-01-30 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0011_cancelamento_solicitado'),
        ('core', '0002_empresa_remove_pessoa_workspaces_alter_cargo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='participantes',
            field=models.ManyToManyField(blank=True, related_name='projetos_participante', to='core.pessoa'),
        ),
    ]
