# Generated by Django 6.0.1 on 2026-01-30 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0012_projeto_participantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTarefaTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('ordem', models.IntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtarefas_template', to='checklists.checklisttemplate')),
            ],
            options={
                'verbose_name': 'Subtarefa do Template',
                'verbose_name_plural': 'Subtarefas do Template',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
