# Generated by Django 6.0.1 on 2026-02-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0013_subtarefatemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklisttemplate',
            name='dias_semana_ativos',
            field=models.CharField(default='0,1,2,3,4', help_text='Dias da semana ativos (0=Seg, 1=Ter, 2=Qua, 3=Qui, 4=Sex, 5=Sáb, 6=Dom)', max_length=20),
        ),
    ]
