# Generated by Django 5.2.10 on 2026-02-07 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0014_dias_semana_ativos'),
        ('core', '0006_add_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetoTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('descricao', models.TextField(blank=True)),
                ('cor', models.CharField(default='#6366f1', help_text='Cor em hex', max_length=7)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template de Projeto',
                'verbose_name_plural': 'Templates de Projeto',
                'ordering': ['titulo'],
            },
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição específica desta tarefa (sobrescreve o template)'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='processo',
            field=models.TextField(blank=True, help_text='Processo específico desta tarefa (sobrescreve o template)'),
        ),
        migrations.AddField(
            model_name='demanda',
            name='tipo_etapa',
            field=models.CharField(choices=[('desenvolvimento', 'Desenvolvimento'), ('melhoria', 'Melhoria')], default='desenvolvimento', help_text='Tipo da etapa: desenvolvimento inicial ou melhoria', max_length=20),
        ),
        migrations.AddField(
            model_name='projeto',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos', to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('planejamento', 'Planejamento'), ('em_andamento', 'Em Andamento'), ('em_manutencao', 'Em Manutenção'), ('pausado', 'Pausado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='planejamento', max_length=20),
        ),
        migrations.CreateModel(
            name='EtapaTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('descricao', models.TextField(blank=True)),
                ('ordem', models.IntegerField(default=0)),
                ('tempo_estimado', models.IntegerField(blank=True, help_text='Tempo estimado em minutos', null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='checklists.projetotemplate')),
            ],
            options={
                'verbose_name': 'Etapa do Template',
                'verbose_name_plural': 'Etapas do Template',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.AddField(
            model_name='projeto',
            name='template_origem',
            field=models.ForeignKey(blank=True, help_text='Template usado para criar este projeto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_criados', to='checklists.projetotemplate'),
        ),
    ]
