# Generated by Django 5.2.10 on 2026-02-07 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0015_add_projeto_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapaMentalNo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ideia', 'Ideia'), ('nota', 'Nota'), ('recurso', 'Recurso'), ('risco', 'Risco'), ('link', 'Link')], default='ideia', max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('cor', models.CharField(default='#94a3b8', help_text='Cor do nó (hex)', max_length=7)),
                ('url', models.URLField(blank=True, help_text='Link externo (opcional)')),
                ('posicao_x', models.IntegerField(default=0, help_text='Posição X no canvas')),
                ('posicao_y', models.IntegerField(default=0, help_text='Posição Y no canvas')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('conectado_a_etapa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nos_conectados', to='checklists.demanda')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nos_mapa', to='checklists.projeto')),
            ],
            options={
                'verbose_name': 'Nó do Mapa Mental',
                'verbose_name_plural': 'Nós do Mapa Mental',
                'ordering': ['criado_em'],
            },
        ),
    ]
