# Generated by Django 5.2.10 on 2026-02-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0016_add_mapa_mental'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklisttemplate',
            name='responsavel_todos',
            field=models.BooleanField(default=False, help_text='Atribuir a TODOS os funcionários'),
        ),
    ]
