# Generated by Django 5.2.10 on 2026-04-04 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0018_anotacao_bloco_notas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklisttemplate',
            options={'ordering': ['horario_sugerido', 'ordem_execucao', '-prioridade', 'titulo'], 'verbose_name': 'Rotina Diária', 'verbose_name_plural': 'Rotinas Diárias'},
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='horario_sugerido',
            field=models.TimeField(blank=True, help_text='Horário sugerido para execução (ex: 08:00)', null=True),
        ),
    ]
