# Generated by Django 6.0.1 on 2026-01-27 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checklists', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacaoWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('lembrete', 'Lembrete'), ('cobranca', 'Cobrança'), ('confirmacao', 'Confirmação')], max_length=20)),
                ('mensagem', models.TextField()),
                ('telefone', models.CharField(max_length=20)),
                ('enviado', models.BooleanField(default=False)),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('erro', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('checklist_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='checklists.checklistitem')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='core.pessoa')),
            ],
            options={
                'verbose_name': 'Notificação WhatsApp',
                'verbose_name_plural': 'Notificações WhatsApp',
                'ordering': ['-criado_em'],
            },
        ),
    ]
