# Generated by Django 6.0.1 on 2026-01-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendamentoNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('lembrete_diario', 'Lembrete Diário (funcionários)'), ('cobranca_funcionarios', 'Cobrança Funcionários'), ('cobranca_externos', 'Cobrança Pessoas Externas')], max_length=30, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('horario', models.TimeField(default='09:00', help_text='Horário de envio')),
                ('dias_semana', models.CharField(default='seg,ter,qua,qui,sex', help_text='Dias separados por vírgula: seg,ter,qua,qui,sex,sab,dom', max_length=50)),
                ('ultima_execucao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Agendamento de Notificação',
                'verbose_name_plural': 'Agendamentos de Notificações',
            },
        ),
    ]
