# Generated by Django 6.0.1 on 2026-01-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_agendamentonotificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamentonotificacao',
            name='tipo',
            field=models.CharField(choices=[('lembrete_diario', 'Lembrete Diário (funcionários)'), ('cobranca_funcionarios', 'Cobrança Funcionários'), ('cobranca_externos', 'Cobrança Pessoas Externas'), ('resumo_dependencias', 'Resumo das Minhas Dependências')], max_length=30, unique=True),
        ),
    ]
