# Generated by Django 6.0.1 on 2026-01-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_agendamentonotificacao_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamentonotificacao',
            name='nome',
            field=models.CharField(blank=True, help_text='Rótulo opcional (ex: Lembrete Manhã, Lembrete Tarde)', max_length=100),
        ),
        migrations.AlterField(
            model_name='agendamentonotificacao',
            name='tipo',
            field=models.CharField(choices=[('lembrete_diario', 'Lembrete Diário (funcionários)'), ('cobranca_funcionarios', 'Cobrança Funcionários'), ('cobranca_externos', 'Cobrança Pessoas Externas'), ('resumo_dependencias', 'Resumo das Minhas Dependências')], max_length=30),
        ),
    ]
