# Generated by Django 6.0.1 on 2026-01-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_agendamentonotificacao_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamentonotificacao',
            name='dia_mes',
            field=models.IntegerField(blank=True, help_text='Dia do mês para recorrência mensal (1-31)', null=True),
        ),
        migrations.AddField(
            model_name='agendamentonotificacao',
            name='recorrencia',
            field=models.CharField(choices=[('diario', 'Diário (dias da semana)'), ('semanal', 'Semanal (um dia fixo)'), ('mensal', 'Mensal (dia do mês)')], default='diario', max_length=10),
        ),
    ]
